"""
Bollinger Band Squeeze + Breakout Strategy.

Detects periods of low volatility compression (the "squeeze") where
Bollinger Bands contract inside Keltner Channels, then generates signals
when price breaks out of the squeeze.  This is a well-known mean-reversion
→ trend-following transition pattern.

Squeeze detection
-----------------
A squeeze occurs when the Bollinger Band width (upper - lower) / middle
falls below a threshold, OR when the BB bands are inside the Keltner
Channel bands.  Squeezes precede directional breakouts ~70% of the time.

Signal logic
------------
- BUY: squeeze was active in last N bars AND close > upper BB (upward breakout)
- SELL: squeeze was active in last N bars AND close < lower BB (downward breakout)
- No signal during squeeze (compression phase — wait for breakout)

Indicators used
---------------
- Bollinger Bands: SMA ± k × σ  (default k=2, period=20)
- Keltner Channels: EMA ± m × ATR  (default m=1.5, ATR period=20)
- BB Width: (upper - lower) / middle  (squeeze when < threshold)
"""

from __future__ import annotations

import logging
import math
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Deque, Dict, List, Optional

logger = logging.getLogger(__name__)

# Maximum number of bars retained per symbol
_MAX_BAR_HISTORY = 500


@dataclass
class BBSqueezSignal:
    """Signal generated by the BB Squeeze strategy."""

    symbol: str
    direction: str  # "buy" or "sell"
    confidence: float  # 0.0 – 1.0
    bb_width: float
    squeeze_bars: int  # how many bars the squeeze lasted
    breakout_strength: float  # magnitude of breakout vs band edge
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def side(self) -> str:
        return self.direction


@dataclass
class _Bar:
    """Internal OHLCV bar."""

    close: float
    high: float
    low: float
    volume: float
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class BBSqueezeStrategy:
    """
    Bollinger Band Squeeze + Breakout strategy.

    Parameters
    ----------
    bb_period : int
        Lookback period for Bollinger Band SMA and standard deviation.
    bb_std : float
        Number of standard deviations for BB upper/lower bands.
    squeeze_threshold : float
        BB width below this value is considered a squeeze.
    keltner_mult : float
        ATR multiplier for Keltner Channel bands.
    keltner_period : int
        ATR lookback period for Keltner Channels.
    squeeze_lookback : int
        Number of bars after squeeze ends during which a breakout is valid.
    min_volume_ratio : float
        Breakout bar volume must be >= this × average volume to confirm.
    """

    def __init__(
        self,
        bb_period: int = 20,
        bb_std: float = 2.0,
        squeeze_threshold: float = 0.03,
        keltner_mult: float = 1.5,
        keltner_period: int = 20,
        squeeze_lookback: int = 5,
        min_volume_ratio: float = 1.2,
    ) -> None:
        self.bb_period = max(bb_period, 5)
        self.bb_std = max(bb_std, 0.5)
        self.squeeze_threshold = max(squeeze_threshold, 0.001)
        self.keltner_mult = max(keltner_mult, 0.5)
        self.keltner_period = max(keltner_period, 5)
        self.squeeze_lookback = max(squeeze_lookback, 1)
        self.min_volume_ratio = max(min_volume_ratio, 0.0)

        # Per-symbol bar history
        self._bars: Dict[str, Deque[_Bar]] = {}
        # Consecutive squeeze bar count
        self._squeeze_count: Dict[str, int] = {}
        # Bars since last squeeze ended
        self._bars_since_squeeze: Dict[str, int] = {}
        # Last squeeze duration (for signal metadata)
        self._last_squeeze_duration: Dict[str, int] = {}

        logger.info(
            "BBSqueezeStrategy initialised (bb=%d/%.1f, keltner=%.1f/%d, "
            "squeeze_threshold=%.4f, lookback=%d)",
            self.bb_period,
            self.bb_std,
            self.keltner_mult,
            self.keltner_period,
            self.squeeze_threshold,
            self.squeeze_lookback,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def update(
        self,
        symbol: str,
        close: float,
        high: float,
        low: float,
        volume: float,
    ) -> None:
        """
        Feed a new OHLCV bar for *symbol*.

        Call once per bar (e.g. every 1-minute or 5-minute candle).
        The strategy accumulates history internally.
        """
        if close <= 0 or high <= 0 or low <= 0:
            logger.warning("BBSqueeze: invalid bar for %s (c=%.4f h=%.4f l=%.4f)", symbol, close, high, low)
            return

        if symbol not in self._bars:
            self._bars[symbol] = deque(maxlen=_MAX_BAR_HISTORY)
            self._squeeze_count[symbol] = 0
            self._bars_since_squeeze[symbol] = 999
            self._last_squeeze_duration[symbol] = 0

        self._bars[symbol].append(_Bar(close=close, high=high, low=low, volume=volume))

        # Update squeeze tracking
        if self.detect_squeeze(symbol):
            self._squeeze_count[symbol] += 1
            self._bars_since_squeeze[symbol] = 0
        else:
            if self._squeeze_count[symbol] > 0:
                # Squeeze just ended
                self._last_squeeze_duration[symbol] = self._squeeze_count[symbol]
                self._squeeze_count[symbol] = 0
            self._bars_since_squeeze[symbol] += 1

    def detect_squeeze(self, symbol: str) -> bool:
        """
        Return ``True`` if *symbol* is currently in a Bollinger Band squeeze.

        A squeeze is detected when:
        1. BB width < ``squeeze_threshold``, OR
        2. BB bands are inside Keltner Channel bands.
        """
        bb = self._calc_bb(symbol)
        kc = self._calc_keltner(symbol)
        if bb is None:
            return False

        bb_upper, bb_middle, bb_lower = bb
        if bb_middle <= 0:
            return False

        bb_width = (bb_upper - bb_lower) / bb_middle

        # Method 1: absolute width threshold
        if bb_width < self.squeeze_threshold:
            return True

        # Method 2: BB inside Keltner Channel
        if kc is not None:
            kc_upper, _, kc_lower = kc
            if bb_upper < kc_upper and bb_lower > kc_lower:
                return True

        return False

    def get_signal(self, symbol: str) -> Optional[BBSqueezSignal]:
        """
        Generate a signal if a squeeze breakout is detected.

        Returns ``None`` if there is no breakout or insufficient data.
        """
        bars = self._bars.get(symbol)
        if not bars or len(bars) < self.bb_period:
            return None

        bb = self._calc_bb(symbol)
        if bb is None:
            return None

        bb_upper, bb_middle, bb_lower = bb
        if bb_middle <= 0:
            return None

        bb_width = (bb_upper - bb_lower) / bb_middle
        current_close = bars[-1].close

        # Only signal if we recently exited a squeeze
        bars_since = self._bars_since_squeeze.get(symbol, 999)
        squeeze_duration = self._last_squeeze_duration.get(symbol, 0)

        # Currently in squeeze → no signal yet
        if self._squeeze_count.get(symbol, 0) > 0:
            return None

        # Too long since squeeze → no signal
        if bars_since > self.squeeze_lookback:
            return None

        if squeeze_duration < 2:
            return None

        # Volume confirmation
        if not self._volume_confirmed(symbol):
            logger.debug("BBSqueeze %s: breakout not volume-confirmed", symbol)
            return None

        direction: Optional[str] = None
        breakout_strength = 0.0

        if current_close > bb_upper:
            direction = "buy"
            breakout_strength = (current_close - bb_upper) / bb_middle if bb_middle > 0 else 0.0
        elif current_close < bb_lower:
            direction = "sell"
            breakout_strength = (bb_lower - current_close) / bb_middle if bb_middle > 0 else 0.0

        if direction is None:
            return None

        # Confidence: based on squeeze duration + breakout strength
        squeeze_conf = min(squeeze_duration / 20.0, 0.5)  # longer squeeze = higher confidence
        breakout_conf = min(breakout_strength * 10.0, 0.5)
        confidence = min(squeeze_conf + breakout_conf, 1.0)

        signal = BBSqueezSignal(
            symbol=symbol,
            direction=direction,
            confidence=round(confidence, 4),
            bb_width=round(bb_width, 6),
            squeeze_bars=squeeze_duration,
            breakout_strength=round(breakout_strength, 6),
        )
        logger.info(
            "BBSqueeze signal: %s %s conf=%.3f (squeeze=%d bars, width=%.4f, breakout=%.4f)",
            symbol, direction, confidence, squeeze_duration, bb_width, breakout_strength,
        )
        return signal

    def get_bb_width(self, symbol: str) -> Optional[float]:
        """Return current Bollinger Band width for *symbol*, or None."""
        bb = self._calc_bb(symbol)
        if bb is None:
            return None
        bb_upper, bb_middle, bb_lower = bb
        if bb_middle <= 0:
            return None
        return (bb_upper - bb_lower) / bb_middle

    # ------------------------------------------------------------------
    # Indicator calculations
    # ------------------------------------------------------------------

    def _calc_bb(self, symbol: str) -> Optional[tuple]:
        """Calculate Bollinger Bands → (upper, middle, lower) or None."""
        bars = self._bars.get(symbol)
        if not bars or len(bars) < self.bb_period:
            return None

        closes = [b.close for b in list(bars)[-self.bb_period:]]
        sma = sum(closes) / len(closes)
        variance = sum((c - sma) ** 2 for c in closes) / len(closes)
        std = math.sqrt(variance)

        upper = sma + self.bb_std * std
        lower = sma - self.bb_std * std
        return upper, sma, lower

    def _calc_keltner(self, symbol: str) -> Optional[tuple]:
        """Calculate Keltner Channels → (upper, middle, lower) or None."""
        bars = self._bars.get(symbol)
        if not bars or len(bars) < self.keltner_period:
            return None

        recent = list(bars)[-self.keltner_period:]
        closes = [b.close for b in recent]

        # EMA (approximated as exponentially weighted)
        ema = closes[0]
        multiplier = 2.0 / (self.keltner_period + 1)
        for c in closes[1:]:
            ema = c * multiplier + ema * (1 - multiplier)

        # ATR
        atr_values: List[float] = []
        for i, bar in enumerate(recent):
            tr = bar.high - bar.low
            if i > 0:
                prev_close = recent[i - 1].close
                tr = max(tr, abs(bar.high - prev_close), abs(bar.low - prev_close))
            atr_values.append(tr)

        atr = sum(atr_values) / len(atr_values) if atr_values else 0.0

        upper = ema + self.keltner_mult * atr
        lower = ema - self.keltner_mult * atr
        return upper, ema, lower

    def _volume_confirmed(self, symbol: str) -> bool:
        """Check if the latest bar's volume exceeds the average by min_volume_ratio."""
        if self.min_volume_ratio <= 0:
            return True

        bars = self._bars.get(symbol)
        if not bars or len(bars) < self.bb_period:
            return True  # Not enough data; don't block on volume

        volumes = [b.volume for b in list(bars)[-self.bb_period:]]
        avg_vol = sum(volumes) / len(volumes) if volumes else 0.0
        if avg_vol <= 0:
            return True

        current_vol = bars[-1].volume
        return current_vol >= avg_vol * self.min_volume_ratio
