"""
Seasonal Pattern Strategy — day-of-week and hour-of-day return effects.

Crypto markets exhibit well-documented calendar anomalies:
- Weekend effect: lower liquidity → higher volatility and different returns
- Hour-of-day effect: Asian/European/US session opens create patterns
- Day-of-week effect: Monday dips, mid-week strength observed historically

This module records historical returns bucketed by (hour, day_of_week),
builds a statistical model of seasonal biases, and generates trading
signals when the current time coincides with historically strong/weak
periods — but only after accumulating 30+ days of data per symbol.

All data is persisted to SQLite so that patterns survive restarts.
"""

from __future__ import annotations

import logging
import os
import sqlite3
import threading
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Minimum observations required before generating signals
_MIN_DAYS_DATA = 30
_MIN_OBSERVATIONS_PER_BUCKET = 5

# Default database path
_DEFAULT_DB_PATH = "data/seasonal_patterns.db"


@dataclass
class SeasonalSignal:
    """Signal generated by the seasonal pattern strategy."""

    symbol: str
    direction: str  # "buy" or "sell"
    confidence: float  # 0.0 – 1.0
    bias: float  # -1.0 to 1.0
    hour: Optional[int]
    day_of_week: Optional[int]
    avg_return: float
    sample_size: int
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class SeasonalPatternStrategy:
    """
    Day-of-week and hour-of-day seasonal return analysis.

    Records historical returns indexed by (hour, day_of_week) and builds
    a statistical bias model.  Generates signals when the current time
    aligns with historically strong/weak windows.

    Parameters
    ----------
    db_path : str
        Path to the SQLite database for persistence.
    min_days : int
        Minimum number of distinct days of data required before signals.
    signal_threshold : float
        Minimum absolute bias value (0–1) to emit a signal.
    """

    def __init__(
        self,
        db_path: str = _DEFAULT_DB_PATH,
        min_days: int = _MIN_DAYS_DATA,
        signal_threshold: float = 0.15,
    ) -> None:
        self.db_path = db_path
        self.min_days = max(min_days, 7)
        self.signal_threshold = max(signal_threshold, 0.01)
        self._lock = threading.Lock()

        # In-memory cache: {symbol: {(hour, dow): [returns]}}
        self._cache: Dict[str, Dict[Tuple[int, int], List[float]]] = defaultdict(
            lambda: defaultdict(list)
        )
        # Track distinct days per symbol
        self._distinct_days: Dict[str, set] = defaultdict(set)

        self._init_db()
        self._load_cache()

        logger.info(
            "SeasonalPatternStrategy initialised (db=%s, min_days=%d, threshold=%.3f)",
            self.db_path,
            self.min_days,
            self.signal_threshold,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def record_return(
        self,
        symbol: str,
        return_pct: float,
        hour: int,
        day_of_week: int,
    ) -> None:
        """
        Record an observed return for a specific hour and day-of-week.

        Parameters
        ----------
        symbol : str
            Trading pair (e.g. ``"BTC/USD"``).
        return_pct : float
            Percentage return (e.g. 0.5 for +0.5%).
        hour : int
            Hour of day (0–23 UTC).
        day_of_week : int
            Day of week (0=Monday … 6=Sunday).
        """
        hour = max(0, min(23, int(hour)))
        day_of_week = max(0, min(6, int(day_of_week)))

        with self._lock:
            self._cache[symbol][(hour, day_of_week)].append(return_pct)
            # Track distinct days using a date-like key
            date_key = f"{day_of_week}_{len(self._cache[symbol][(hour, day_of_week)])}"
            self._distinct_days[symbol].add(
                datetime.now(timezone.utc).strftime("%Y-%m-%d")
            )
            self._persist_return(symbol, return_pct, hour, day_of_week)

    def get_seasonal_bias(
        self,
        symbol: str,
        hour: Optional[int] = None,
        day_of_week: Optional[int] = None,
    ) -> float:
        """
        Return the seasonal bias for *symbol* at the given time.

        The bias is a float from -1.0 (strongly bearish) to 1.0 (strongly
        bullish), derived from the average return at this (hour, dow) bucket
        normalised against the overall average.

        If *hour* or *day_of_week* is ``None``, returns the marginal bias
        for the non-None dimension, or the overall bias if both are None.
        """
        with self._lock:
            return self._compute_bias(symbol, hour, day_of_week)

    def get_best_trading_hours(
        self,
        symbol: str,
        top_n: int = 5,
    ) -> List[Tuple[int, float]]:
        """
        Return the best trading hours for *symbol* sorted by avg return.

        Returns
        -------
        list of (hour, avg_return)
            Sorted descending by average return.
        """
        with self._lock:
            data = self._cache.get(symbol, {})
            hour_returns: Dict[int, List[float]] = defaultdict(list)
            for (h, _dow), rets in data.items():
                hour_returns[h].extend(rets)

            results: List[Tuple[int, float]] = []
            for h, rets in hour_returns.items():
                if len(rets) >= _MIN_OBSERVATIONS_PER_BUCKET:
                    avg = sum(rets) / len(rets)
                    results.append((h, round(avg, 6)))

            results.sort(key=lambda x: x[1], reverse=True)
            return results[:top_n]

    def get_weekend_effect(self, symbol: str) -> float:
        """
        Return the weekend vs weekday return difference.

        Positive value means weekends outperform weekdays on average.
        """
        with self._lock:
            data = self._cache.get(symbol, {})
            weekday_rets: List[float] = []
            weekend_rets: List[float] = []

            for (h, dow), rets in data.items():
                if dow in (5, 6):  # Saturday, Sunday
                    weekend_rets.extend(rets)
                else:
                    weekday_rets.extend(rets)

            if not weekday_rets or not weekend_rets:
                return 0.0

            avg_weekday = sum(weekday_rets) / len(weekday_rets)
            avg_weekend = sum(weekend_rets) / len(weekend_rets)
            return round(avg_weekend - avg_weekday, 6)

    def get_signal(
        self,
        symbol: str,
        hour: Optional[int] = None,
        day_of_week: Optional[int] = None,
    ) -> Optional[SeasonalSignal]:
        """
        Generate a seasonal signal for *symbol* at the given time.

        Returns ``None`` if insufficient data or bias below threshold.
        """
        if not self._has_sufficient_data(symbol):
            return None

        bias = self.get_seasonal_bias(symbol, hour, day_of_week)
        if abs(bias) < self.signal_threshold:
            return None

        direction = "buy" if bias > 0 else "sell"
        confidence = min(abs(bias), 1.0)

        # Get sample size for the bucket
        with self._lock:
            data = self._cache.get(symbol, {})
            sample_size = 0
            avg_ret = 0.0
            if hour is not None and day_of_week is not None:
                rets = data.get((hour, day_of_week), [])
                sample_size = len(rets)
                avg_ret = sum(rets) / len(rets) if rets else 0.0
            else:
                total_rets: List[float] = []
                for (h, dow), rets in data.items():
                    match = True
                    if hour is not None and h != hour:
                        match = False
                    if day_of_week is not None and dow != day_of_week:
                        match = False
                    if match:
                        total_rets.extend(rets)
                sample_size = len(total_rets)
                avg_ret = sum(total_rets) / len(total_rets) if total_rets else 0.0

        signal = SeasonalSignal(
            symbol=symbol,
            direction=direction,
            confidence=round(confidence, 4),
            bias=round(bias, 4),
            hour=hour,
            day_of_week=day_of_week,
            avg_return=round(avg_ret, 6),
            sample_size=sample_size,
        )
        logger.info(
            "Seasonal signal: %s %s bias=%.3f conf=%.3f (h=%s dow=%s n=%d)",
            symbol, direction, bias, confidence, hour, day_of_week, sample_size,
        )
        return signal

    def has_sufficient_data(self, symbol: str) -> bool:
        """Return True if enough data has been collected for *symbol*."""
        return self._has_sufficient_data(symbol)

    def get_data_summary(self, symbol: str) -> Dict:
        """Return a summary of collected data for *symbol*."""
        with self._lock:
            data = self._cache.get(symbol, {})
            total_obs = sum(len(v) for v in data.values())
            distinct_days = len(self._distinct_days.get(symbol, set()))
            return {
                "symbol": symbol,
                "total_observations": total_obs,
                "distinct_days": distinct_days,
                "buckets_populated": len(data),
                "max_possible_buckets": 24 * 7,  # 168
                "sufficient_data": self._has_sufficient_data(symbol),
            }

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _has_sufficient_data(self, symbol: str) -> bool:
        """Check if we have enough data to generate signals."""
        distinct_days = len(self._distinct_days.get(symbol, set()))
        return distinct_days >= self.min_days

    def _compute_bias(
        self,
        symbol: str,
        hour: Optional[int],
        day_of_week: Optional[int],
    ) -> float:
        """Compute normalised bias from -1 to 1."""
        data = self._cache.get(symbol, {})
        if not data:
            return 0.0

        # Collect all returns
        all_rets: List[float] = []
        for rets in data.values():
            all_rets.extend(rets)
        if not all_rets:
            return 0.0

        overall_avg = sum(all_rets) / len(all_rets)
        overall_std = (
            (sum((r - overall_avg) ** 2 for r in all_rets) / len(all_rets)) ** 0.5
            if len(all_rets) > 1
            else 1.0
        )
        if overall_std <= 0:
            overall_std = 1.0

        # Collect returns for the specified bucket(s)
        bucket_rets: List[float] = []
        for (h, dow), rets in data.items():
            match = True
            if hour is not None and h != hour:
                match = False
            if day_of_week is not None and dow != day_of_week:
                match = False
            if match:
                bucket_rets.extend(rets)

        if len(bucket_rets) < _MIN_OBSERVATIONS_PER_BUCKET:
            return 0.0

        bucket_avg = sum(bucket_rets) / len(bucket_rets)

        # Z-score normalised to [-1, 1] using tanh-like scaling
        z = (bucket_avg - overall_avg) / overall_std
        # Sigmoid-ish clamping
        bias = max(-1.0, min(1.0, z / 2.0))
        return round(bias, 6)

    def _init_db(self) -> None:
        """Create the SQLite database and tables if they don't exist."""
        os.makedirs(os.path.dirname(self.db_path) or ".", exist_ok=True)
        conn = sqlite3.connect(self.db_path)
        try:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS seasonal_returns (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    symbol TEXT NOT NULL,
                    return_pct REAL NOT NULL,
                    hour INTEGER NOT NULL,
                    day_of_week INTEGER NOT NULL,
                    recorded_at TEXT NOT NULL DEFAULT (datetime('now')),
                    date_key TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_seasonal_symbol
                ON seasonal_returns(symbol)
                """
            )
            conn.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_seasonal_bucket
                ON seasonal_returns(symbol, hour, day_of_week)
                """
            )
            conn.commit()
        finally:
            conn.close()

    def _persist_return(
        self,
        symbol: str,
        return_pct: float,
        hour: int,
        day_of_week: int,
    ) -> None:
        """Write a return observation to the database."""
        date_key = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        try:
            conn = sqlite3.connect(self.db_path)
            try:
                conn.execute(
                    """
                    INSERT INTO seasonal_returns (symbol, return_pct, hour, day_of_week, date_key)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (symbol, return_pct, hour, day_of_week, date_key),
                )
                conn.commit()
            finally:
                conn.close()
        except Exception:
            logger.exception("Failed to persist seasonal return for %s", symbol)

    def _load_cache(self) -> None:
        """Load all historical data from the database into memory."""
        if not os.path.exists(self.db_path):
            return
        try:
            conn = sqlite3.connect(self.db_path)
            try:
                cursor = conn.execute(
                    "SELECT symbol, return_pct, hour, day_of_week, date_key FROM seasonal_returns"
                )
                count = 0
                for symbol, ret, hour, dow, date_key in cursor:
                    self._cache[symbol][(hour, dow)].append(ret)
                    self._distinct_days[symbol].add(date_key)
                    count += 1
                if count > 0:
                    logger.info("Loaded %d seasonal return observations from database", count)
            finally:
                conn.close()
        except Exception:
            logger.exception("Failed to load seasonal cache from %s", self.db_path)
