"""
R740 Activation Script — switches ARGUS from SQLite/in-memory to R740 backends.

Run this script AFTER the R740 server is fully provisioned with:
  - TimescaleDB on port 5432
  - Redis on port 6379
  - Kafka on port 9092

Usage:
    py scripts/r740_activate.py --host 192.168.1.x --test-only
    py scripts/r740_activate.py --host 192.168.1.x --activate
"""

from __future__ import annotations

import argparse
import json
import os
import socket
import sys
import time
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


def check_port(host: str, port: int, service: str, timeout: float = 5.0) -> bool:
    try:
        sock = socket.create_connection((host, port), timeout=timeout)
        sock.close()
        print(f"  [OK] {service} reachable at {host}:{port}")
        return True
    except OSError as exc:
        print(f"  [FAIL] {service} at {host}:{port} — {exc}")
        return False


def test_timescaledb(host: str, password: str = "argus") -> bool:
    try:
        import psycopg2  # type: ignore
        conn = psycopg2.connect(
            host=host, port=5432, dbname="argus", user="argus",
            password=password, connect_timeout=5,
        )
        cur = conn.cursor()
        cur.execute("SELECT version()")
        ver = cur.fetchone()[0]
        conn.close()
        print(f"  [OK] TimescaleDB connected: {ver[:60]}")
        return True
    except ImportError:
        print("  [WARN] psycopg2 not installed — run: pip install psycopg2-binary")
        return False
    except Exception as exc:
        print(f"  [FAIL] TimescaleDB connection error: {exc}")
        return False


def test_redis(host: str) -> bool:
    try:
        import redis  # type: ignore
        r = redis.Redis(host=host, port=6379, socket_timeout=5)
        pong = r.ping()
        if pong:
            info = r.info("server")
            print(f"  [OK] Redis connected: v{info.get('redis_version', '?')}")
        return True
    except ImportError:
        print("  [WARN] redis-py not installed — run: pip install redis")
        return False
    except Exception as exc:
        print(f"  [FAIL] Redis connection error: {exc}")
        return False


def test_kafka(host: str) -> bool:
    try:
        from kafka import KafkaAdminClient  # type: ignore
        admin = KafkaAdminClient(
            bootstrap_servers=f"{host}:9092",
            request_timeout_ms=5000,
        )
        topics = admin.list_topics()
        admin.close()
        print(f"  [OK] Kafka connected, {len(topics)} topics")
        return True
    except ImportError:
        print("  [WARN] kafka-python not installed — run: pip install kafka-python")
        return False
    except Exception as exc:
        print(f"  [FAIL] Kafka connection error: {exc}")
        return False


def write_env_file(host: str, db_password: str = "argus") -> None:
    env_path = BASE_DIR / ".env.r740"
    content = f"""# ARGUS R740 Backend Configuration
# Generated by scripts/r740_activate.py
# Source this file before starting ARGUS: source .env.r740

# TimescaleDB (replaces SQLite)
ARGUS_DATABASE_URL=postgresql://argus:{db_password}@{host}:5432/argus

# Redis (replaces in-memory state)
ARGUS_REDIS_URL=redis://{host}:6379/0

# Kafka (event streaming)
ARGUS_KAFKA_BROKERS={host}:9092

# Activate R740 config profile (enables infra section in unified_config.yaml)
ARGUS_CONFIG_PROFILE=r740

# Monitoring stack
ARGUS_PROMETHEUS_GATEWAY=http://{host}:9091
ARGUS_LOKI_URL=http://{host}:3100
"""
    env_path.write_text(content)
    print(f"\n[OK] Environment file written: {env_path}")
    print("     To activate: $env:ARGUS_DATABASE_URL = ... (PowerShell)")
    print("     Or add to your shell profile / docker-compose.r740.yml")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Test and activate R740 backends for ARGUS"
    )
    parser.add_argument("--host", required=True, help="R740 server IP address")
    parser.add_argument("--db-password", default="argus", help="TimescaleDB password")
    parser.add_argument("--test-only", action="store_true",
                        help="Test connectivity only, don't write env file")
    parser.add_argument("--activate", action="store_true",
                        help="Write .env.r740 file with backend configuration")
    args = parser.parse_args()

    host = args.host
    print(f"\n=== R740 Connectivity Test ({host}) ===\n")

    # Port-level checks
    results = {
        "timescaledb_port": check_port(host, 5432, "TimescaleDB"),
        "redis_port": check_port(host, 6379, "Redis"),
        "kafka_port": check_port(host, 9092, "Kafka"),
        "grafana_port": check_port(host, 3000, "Grafana"),
        "prometheus_port": check_port(host, 9090, "Prometheus"),
    }

    print("\n=== Service-Level Tests ===\n")
    if results["timescaledb_port"]:
        results["timescaledb_db"] = test_timescaledb(host, args.db_password)
    if results["redis_port"]:
        results["redis_db"] = test_redis(host)
    if results["kafka_port"]:
        results["kafka_db"] = test_kafka(host)

    all_core = all([
        results.get("timescaledb_port"),
        results.get("redis_port"),
        results.get("kafka_port"),
    ])

    print(f"\n=== Summary ===\n")
    print(f"  Core backends ready: {'YES' if all_core else 'NO (some services not reachable)'}")

    if not all_core:
        print("\nCheck that docker-compose.r740.yml is running on the R740:")
        print("  docker compose -f docker-compose.r740.yml up -d")
        if not args.activate:
            sys.exit(1)

    if args.activate or (all_core and not args.test_only):
        print()
        write_env_file(host, args.db_password)
        print("\n[INFO] Next steps:")
        print("  1. Set environment variables from .env.r740")
        print("  2. Run schema migration: py scripts/migrate_to_timescale.py")
        print("  3. Restart ARGUS: py main.py paper")
    else:
        print("\nRun with --activate to write the environment config file.")


if __name__ == "__main__":
    main()
