"""
Universal Trading Strategies
=============================
Every known trading strategy type implemented and ready to use.

Strategy Categories:
1. Trend Following - Ride trends until they reverse
2. Mean Reversion - Bet on prices returning to average
3. Momentum - Follow price acceleration
4. Breakout - Trade breakouts from ranges
5. Scalping - Quick small profits
6. Swing Trading - Capture medium-term moves
7. Statistical Arbitrage - Exploit statistical inefficiencies
8. Market Making - Provide liquidity for profit
9. Pairs Trading - Correlated asset pairs
10. Event-Driven - Trade news/events
11. Volume Profile - Trade based on volume distribution
12. Order Flow - Read the tape
"""

from __future__ import annotations

import logging
import time
from abc import ABC, abstractmethod
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Deque, Dict, List, Optional, Tuple

import numpy as np

logger = logging.getLogger(__name__)


# ============================================================================
# BASE STRATEGY CLASS
# ============================================================================

@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    action: str  # buy, sell, hold
    confidence: float  # 0-1
    strategy: str
    reason: str
    strength: float  # How strong the signal is
    metadata: Dict[str, Any] = field(default_factory=dict)


class TradingStrategy(ABC):
    """Base class for all trading strategies."""
    
    def __init__(self, name: str, timeframe: str = "1m"):
        self.name = name
        self.timeframe = timeframe
        self.enabled = True
        self.weight: float = 1.0  # For ensemble weighting
        
        # Performance tracking
        self.signals_generated: int = 0
        self.winning_signals: int = 0
        self.total_pnl: float = 0.0
        self.recent_performance: Deque[float] = deque(maxlen=100)
    
    @abstractmethod
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        """Analyze prices and generate signal."""
        pass
    
    def record_outcome(self, pnl: float) -> None:
        """Record outcome of a trade based on this strategy's signal."""
        self.total_pnl += pnl
        self.recent_performance.append(pnl)
        if pnl > 0:
            self.winning_signals += 1
    
    def get_win_rate(self) -> float:
        """Get win rate."""
        if self.signals_generated == 0:
            return 0.5
        return self.winning_signals / self.signals_generated
    
    def get_score(self) -> float:
        """Get strategy score for weighting."""
        if len(self.recent_performance) < 10:
            return 0.5
        
        recent = list(self.recent_performance)
        mean_pnl = np.mean(recent)
        std_pnl = np.std(recent) if np.std(recent) > 0 else 0.001
        
        # Sharpe-like score
        return max(0.1, 0.5 + mean_pnl / std_pnl * 0.1)


# ============================================================================
# 1. TREND FOLLOWING STRATEGIES
# ============================================================================

class SMACrossover(TradingStrategy):
    """Simple Moving Average Crossover strategy."""
    
    def __init__(self, fast_period: int = 10, slow_period: int = 30):
        super().__init__(f"SMA_Cross_{fast_period}_{slow_period}")
        self.fast_period = fast_period
        self.slow_period = slow_period
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < self.slow_period:
            return None
        
        fast_sma = np.mean(prices[-self.fast_period:])
        slow_sma = np.mean(prices[-self.slow_period:])
        
        prev_fast = np.mean(prices[-self.fast_period-1:-1])
        prev_slow = np.mean(prices[-self.slow_period-1:-1])
        
        # Bullish crossover
        if prev_fast <= prev_slow and fast_sma > slow_sma:
            strength = (fast_sma - slow_sma) / slow_sma
            return Signal(
                action="buy",
                confidence=min(0.8, 0.5 + strength * 10),
                strategy=self.name,
                reason=f"SMA bullish crossover: {self.fast_period} crossed above {self.slow_period}",
                strength=strength,
            )
        
        # Bearish crossover
        if prev_fast >= prev_slow and fast_sma < slow_sma:
            strength = (slow_sma - fast_sma) / slow_sma
            return Signal(
                action="sell",
                confidence=min(0.8, 0.5 + strength * 10),
                strategy=self.name,
                reason=f"SMA bearish crossover: {self.fast_period} crossed below {self.slow_period}",
                strength=strength,
            )
        
        return None


class EMACrossover(TradingStrategy):
    """Exponential Moving Average Crossover."""
    
    def __init__(self, fast_period: int = 12, slow_period: int = 26):
        super().__init__(f"EMA_Cross_{fast_period}_{slow_period}")
        self.fast_period = fast_period
        self.slow_period = slow_period
    
    def _ema(self, prices: List[float], period: int) -> float:
        """Calculate EMA."""
        multiplier = 2 / (period + 1)
        ema = prices[0]
        for price in prices[1:]:
            ema = (price - ema) * multiplier + ema
        return ema
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < self.slow_period:
            return None
        
        fast_ema = self._ema(prices[-self.fast_period:], self.fast_period)
        slow_ema = self._ema(prices[-self.slow_period:], self.slow_period)
        
        prev_fast = self._ema(prices[-self.fast_period-1:-1], self.fast_period)
        prev_slow = self._ema(prices[-self.slow_period-1:-1], self.slow_period)
        
        if prev_fast <= prev_slow and fast_ema > slow_ema:
            return Signal(
                action="buy",
                confidence=0.65,
                strategy=self.name,
                reason="EMA bullish crossover",
                strength=abs(fast_ema - slow_ema) / slow_ema,
            )
        elif prev_fast >= prev_slow and fast_ema < slow_ema:
            return Signal(
                action="sell",
                confidence=0.65,
                strategy=self.name,
                reason="EMA bearish crossover",
                strength=abs(slow_ema - fast_ema) / slow_ema,
            )
        
        return None


class ADXTrendStrength(TradingStrategy):
    """ADX-based trend strength strategy."""
    
    def __init__(self, period: int = 14, threshold: float = 25.0):
        super().__init__(f"ADX_Trend_{period}")
        self.period = period
        self.threshold = threshold
    
    def _calc_adx(self, prices: List[float]) -> float:
        """Simplified ADX calculation."""
        if len(prices) < self.period + 1:
            return 0.0
        
        # Calculate true range (simplified)
        tr_values = []
        for i in range(1, len(prices)):
            tr = abs(prices[i] - prices[i-1])
            tr_values.append(tr)
        
        # Calculate directional movement
        up_moves = []
        down_moves = []
        for i in range(1, len(prices)):
            up = prices[i] - prices[i-1] if prices[i] > prices[i-1] else 0
            down = prices[i-1] - prices[i] if prices[i] < prices[i-1] else 0
            up_moves.append(up)
            down_moves.append(down)
        
        # Simplified ADX
        avg_tr = np.mean(tr_values[-self.period:])
        avg_up = np.mean(up_moves[-self.period:])
        avg_down = np.mean(down_moves[-self.period:])
        
        if avg_tr == 0:
            return 0.0
        
        plus_di = (avg_up / avg_tr) * 100
        minus_di = (avg_down / avg_tr) * 100
        
        di_sum = plus_di + minus_di
        if di_sum == 0:
            return 0.0
        
        dx = abs(plus_di - minus_di) / di_sum * 100
        return dx
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        adx = self._calc_adx(prices)
        
        if adx > self.threshold:
            # Strong trend - follow direction
            recent_return = (prices[-1] - prices[-5]) / prices[-5]
            
            if recent_return > 0:
                return Signal(
                    action="buy",
                    confidence=min(0.8, 0.5 + adx / 100),
                    strategy=self.name,
                    reason=f"Strong uptrend (ADX={adx:.1f})",
                    strength=adx / 100,
                )
            else:
                return Signal(
                    action="sell",
                    confidence=min(0.8, 0.5 + adx / 100),
                    strategy=self.name,
                    reason=f"Strong downtrend (ADX={adx:.1f})",
                    strength=adx / 100,
                )
        
        return None


class ParabolicSAR(TradingStrategy):
    """Parabolic SAR trend following."""
    
    def __init__(self, af_start: float = 0.02, af_increment: float = 0.02, af_max: float = 0.2):
        super().__init__("ParabolicSAR")
        self.af_start = af_start
        self.af_increment = af_increment
        self.af_max = af_max
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < 10:
            return None
        
        # Simplified SAR calculation
        # In real implementation, would track SAR, EP, AF properly
        
        # Calculate trend direction
        recent_trend = np.mean(prices[-5:]) - np.mean(prices[-10:-5])
        
        # SAR would be below prices in uptrend, above in downtrend
        sar_value = prices[-1] * (1 - 0.01 * np.sign(recent_trend))
        
        if recent_trend > 0 and prices[-1] > sar_value:
            return Signal(
                action="buy",
                confidence=0.6,
                strategy=self.name,
                reason="SAR below price in uptrend",
                strength=abs(recent_trend) / prices[-1],
            )
        elif recent_trend < 0 and prices[-1] < sar_value:
            return Signal(
                action="sell",
                confidence=0.6,
                strategy=self.name,
                reason="SAR above price in downtrend",
                strength=abs(recent_trend) / prices[-1],
            )
        
        return None


# ============================================================================
# 2. MOMENTUM STRATEGIES
# ============================================================================

class RSIMomentum(TradingStrategy):
    """RSI-based momentum strategy."""
    
    def __init__(self, period: int = 14, overbought: float = 70, oversold: float = 30):
        super().__init__(f"RSI_{period}")
        self.period = period
        self.overbought = overbought
        self.oversold = oversold
    
    def _calc_rsi(self, prices: List[float]) -> float:
        """Calculate RSI."""
        if len(prices) < self.period + 1:
            return 50.0
        
        deltas = np.diff(prices[-self.period-1:])
        gains = deltas[deltas > 0].sum()
        losses = abs(deltas[deltas < 0].sum())
        
        if losses == 0:
            return 100.0
        
        rs = gains / losses
        rsi = 100 - (100 / (1 + rs))
        return rsi
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        rsi = self._calc_rsi(prices)
        
        # Oversold bounce
        if rsi < self.oversold:
            return Signal(
                action="buy",
                confidence=min(0.8, 0.5 + (self.oversold - rsi) / 30),
                strategy=self.name,
                reason=f"RSI oversold ({rsi:.1f})",
                strength=(self.oversold - rsi) / 30,
            )
        
        # Overbought reversal
        if rsi > self.overbought:
            return Signal(
                action="sell",
                confidence=min(0.8, 0.5 + (rsi - self.overbought) / 30),
                strategy=self.name,
                reason=f"RSI overbought ({rsi:.1f})",
                strength=(rsi - self.overbought) / 30,
            )
        
        # Momentum continuation
        if 50 < rsi < 60:
            return Signal(
                action="buy",
                confidence=0.4,
                strategy=self.name,
                reason=f"RSI momentum ({rsi:.1f})",
                strength=(rsi - 50) / 50,
            )
        
        return None


class MACDMomentum(TradingStrategy):
    """MACD momentum strategy."""
    
    def __init__(self, fast: int = 12, slow: int = 26, signal: int = 9):
        super().__init__(f"MACD_{fast}_{slow}_{signal}")
        self.fast = fast
        self.slow = slow
        self.signal_period = signal
    
    def _ema(self, prices: List[float], period: int) -> List[float]:
        """Calculate EMA series."""
        multiplier = 2 / (period + 1)
        ema_values = [prices[0]]
        for price in prices[1:]:
            ema_values.append((price - ema_values[-1]) * multiplier + ema_values[-1])
        return ema_values
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < self.slow + self.signal_period:
            return None
        
        # Calculate MACD
        fast_ema = self._ema(prices, self.fast)
        slow_ema = self._ema(prices, self.slow)
        
        macd_line = [f - s for f, s in zip(fast_ema, slow_ema)]
        signal_line = self._ema(macd_line, self.signal_period)
        
        # Current and previous values
        macd_current = macd_line[-1]
        signal_current = signal_line[-1]
        macd_prev = macd_line[-2]
        signal_prev = signal_line[-2]
        
        # Bullish crossover
        if macd_prev <= signal_prev and macd_current > signal_current:
            return Signal(
                action="buy",
                confidence=0.7,
                strategy=self.name,
                reason="MACD bullish crossover",
                strength=abs(macd_current - signal_current) / abs(signal_current) if signal_current != 0 else 0.5,
            )
        
        # Bearish crossover
        if macd_prev >= signal_prev and macd_current < signal_current:
            return Signal(
                action="sell",
                confidence=0.7,
                strategy=self.name,
                reason="MACD bearish crossover",
                strength=abs(signal_current - macd_current) / abs(signal_current) if signal_current != 0 else 0.5,
            )
        
        return None


class ROCMomentum(TradingStrategy):
    """Rate of Change momentum strategy."""
    
    def __init__(self, period: int = 10, threshold: float = 0.02):
        super().__init__(f"ROC_{period}")
        self.period = period
        self.threshold = threshold
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < self.period + 1:
            return None
        
        roc = (prices[-1] - prices[-self.period-1]) / prices[-self.period-1]
        
        if roc > self.threshold:
            return Signal(
                action="buy",
                confidence=min(0.8, 0.5 + roc / 0.1),
                strategy=self.name,
                reason=f"Strong positive momentum (ROC={roc:.2%})",
                strength=roc / 0.1,
            )
        elif roc < -self.threshold:
            return Signal(
                action="sell",
                confidence=min(0.8, 0.5 + abs(roc) / 0.1),
                strategy=self.name,
                reason=f"Strong negative momentum (ROC={roc:.2%})",
                strength=abs(roc) / 0.1,
            )
        
        return None


class StochasticMomentum(TradingStrategy):
    """Stochastic oscillator momentum strategy."""
    
    def __init__(self, k_period: int = 14, d_period: int = 3):
        super().__init__(f"Stochastic_{k_period}_{d_period}")
        self.k_period = k_period
        self.d_period = d_period
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < self.k_period:
            return None
        
        # Calculate %K
        highest = max(prices[-self.k_period:])
        lowest = min(prices[-self.k_period:])
        
        if highest == lowest:
            return None
        
        k = (prices[-1] - lowest) / (highest - lowest) * 100
        
        # Oversold bounce
        if k < 20:
            return Signal(
                action="buy",
                confidence=0.6,
                strategy=self.name,
                reason=f"Stochastic oversold ({k:.1f})",
                strength=(20 - k) / 20,
            )
        
        # Overbought reversal
        if k > 80:
            return Signal(
                action="sell",
                confidence=0.6,
                strategy=self.name,
                reason=f"Stochastic overbought ({k:.1f})",
                strength=(k - 80) / 20,
            )
        
        return None


# ============================================================================
# 3. MEAN REVERSION STRATEGIES
# ============================================================================

class BollingerBandReversion(TradingStrategy):
    """Bollinger Bands mean reversion."""
    
    def __init__(self, period: int = 20, num_std: float = 2.0):
        super().__init__(f"Bollinger_{period}_{num_std}")
        self.period = period
        self.num_std = num_std
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < self.period:
            return None
        
        # Calculate bands
        mean = np.mean(prices[-self.period:])
        std = np.std(prices[-self.period:])
        
        upper = mean + self.num_std * std
        lower = mean - self.num_std * std
        
        current = prices[-1]
        
        # Price below lower band - buy (expect reversion to mean)
        if current < lower:
            deviation = (mean - current) / std
            return Signal(
                action="buy",
                confidence=min(0.8, 0.5 + deviation * 0.15),
                strategy=self.name,
                reason=f"Price below lower Bollinger Band (z={deviation:.2f})",
                strength=deviation / self.num_std,
            )
        
        # Price above upper band - sell (expect reversion to mean)
        if current > upper:
            deviation = (current - mean) / std
            return Signal(
                action="sell",
                confidence=min(0.8, 0.5 + deviation * 0.15),
                strategy=self.name,
                reason=f"Price above upper Bollinger Band (z={deviation:.2f})",
                strength=deviation / self.num_std,
            )
        
        return None


class ZScoreReversion(TradingStrategy):
    """Z-Score based mean reversion."""
    
    def __init__(self, period: int = 20, entry_z: float = 2.0, exit_z: float = 0.5):
        super().__init__(f"ZScore_{period}")
        self.period = period
        self.entry_z = entry_z
        self.exit_z = exit_z
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < self.period:
            return None
        
        mean = np.mean(prices[-self.period:])
        std = np.std(prices[-self.period:])
        
        if std == 0:
            return None
        
        z_score = (prices[-1] - mean) / std
        
        if z_score < -self.entry_z:
            return Signal(
                action="buy",
                confidence=min(0.8, 0.5 + abs(z_score) / 10),
                strategy=self.name,
                reason=f"Z-Score oversold ({z_score:.2f})",
                strength=abs(z_score) / self.entry_z,
            )
        elif z_score > self.entry_z:
            return Signal(
                action="sell",
                confidence=min(0.8, 0.5 + abs(z_score) / 10),
                strategy=self.name,
                reason=f"Z-Score overbought ({z_score:.2f})",
                strength=abs(z_score) / self.entry_z,
            )
        
        return None


class RSIReversion(TradingStrategy):
    """RSI mean reversion (different from momentum version)."""
    
    def __init__(self, period: int = 14):
        super().__init__(f"RSI_Reversion_{period}")
        self.period = period
    
    def _calc_rsi(self, prices: List[float]) -> float:
        if len(prices) < self.period + 1:
            return 50.0
        
        deltas = np.diff(prices[-self.period-1:])
        gains = deltas[deltas > 0].sum()
        losses = abs(deltas[deltas < 0].sum())
        
        if losses == 0:
            return 100.0
        
        rs = gains / losses
        return 100 - (100 / (1 + rs))
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        rsi = self._calc_rsi(prices)
        
        # Extreme oversold - strong buy
        if rsi < 20:
            return Signal(
                action="buy",
                confidence=0.8,
                strategy=self.name,
                reason=f"RSI extreme oversold ({rsi:.1f})",
                strength=(20 - rsi) / 20,
            )
        
        # Extreme overbought - strong sell
        if rsi > 80:
            return Signal(
                action="sell",
                confidence=0.8,
                strategy=self.name,
                reason=f"RSI extreme overbought ({rsi:.1f})",
                strength=(rsi - 80) / 20,
            )
        
        return None


# ============================================================================
# 4. BREAKOUT STRATEGIES
# ============================================================================

class RangeBreakout(TradingStrategy):
    """Breakout from consolidation range."""
    
    def __init__(self, lookback: int = 20, breakout_pct: float = 0.005):
        super().__init__(f"RangeBreakout_{lookback}")
        self.lookback = lookback
        self.breakout_pct = breakout_pct
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < self.lookback:
            return None
        
        # Calculate range
        highest = max(prices[-self.lookback:])
        lowest = min(prices[-self.lookback:])
        range_size = highest - lowest
        
        if range_size == 0:
            return None
        
        current = prices[-1]
        
        # Breakout above
        if current > highest * (1 + self.breakout_pct):
            strength = (current - highest) / range_size
            return Signal(
                action="buy",
                confidence=min(0.85, 0.6 + strength),
                strategy=self.name,
                reason=f"Bullish breakout above {self.lookback}-period high",
                strength=strength,
            )
        
        # Breakdown below
        if current < lowest * (1 - self.breakout_pct):
            strength = (lowest - current) / range_size
            return Signal(
                action="sell",
                confidence=min(0.85, 0.6 + strength),
                strategy=self.name,
                reason=f"Bearish breakdown below {self.lookback}-period low",
                strength=strength,
            )
        
        return None


class VolumeBreakout(TradingStrategy):
    """Breakout confirmed by volume."""
    
    def __init__(self, lookback: int = 20, volume_mult: float = 1.5):
        super().__init__(f"VolumeBreakout_{lookback}")
        self.lookback = lookback
        self.volume_mult = volume_mult
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        volumes = kwargs.get("volumes", [])
        
        if len(prices) < self.lookback or len(volumes) < self.lookback:
            return None
        
        highest = max(prices[-self.lookback:])
        lowest = min(prices[-self.lookback:])
        avg_volume = np.mean(volumes[-self.lookback:])
        current_volume = volumes[-1]
        
        # Volume spike + price breakout
        if current_volume > avg_volume * self.volume_mult:
            if prices[-1] > highest:
                return Signal(
                    action="buy",
                    confidence=0.75,
                    strategy=self.name,
                    reason=f"Volume breakout (vol={current_volume/avg_volume:.1f}x avg)",
                    strength=current_volume / avg_volume / self.volume_mult,
                )
            elif prices[-1] < lowest:
                return Signal(
                    action="sell",
                    confidence=0.75,
                    strategy=self.name,
                    reason=f"Volume breakdown (vol={current_volume/avg_volume:.1f}x avg)",
                    strength=current_volume / avg_volume / self.volume_mult,
                )
        
        return None


# ============================================================================
# 5. SCALPING STRATEGIES
# ============================================================================

class SpreadScalping(TradingStrategy):
    """Scalp small price movements."""
    
    def __init__(self, threshold: float = 0.001):
        super().__init__(f"SpreadScalp_{threshold}")
        self.threshold = threshold
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < 5:
            return None
        
        # Quick micro-momentum
        short_momentum = (prices[-1] - prices[-3]) / prices[-3]
        micro_momentum = (prices[-3] - prices[-5]) / prices[-5]
        
        # Scalp in direction of micro-momentum
        if abs(micro_momentum) > self.threshold:
            if micro_momentum > 0 and short_momentum > 0:
                return Signal(
                    action="buy",
                    confidence=0.5,
                    strategy=self.name,
                    reason=f"Micro momentum scalp (mom={micro_momentum:.3%})",
                    strength=abs(micro_momentum) / 0.01,
                )
            elif micro_momentum < 0 and short_momentum < 0:
                return Signal(
                    action="sell",
                    confidence=0.5,
                    strategy=self.name,
                    reason=f"Micro momentum scalp (mom={micro_momentum:.3%})",
                    strength=abs(micro_momentum) / 0.01,
                )
        
        return None


class OrderFlowScalping(TradingStrategy):
    """Scalp based on order flow imbalances."""
    
    def __init__(self, imbalance_threshold: float = 1.5):
        super().__init__(f"OrderFlowScalp")
        self.imbalance_threshold = imbalance_threshold
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        bid_volumes = kwargs.get("bid_volumes", [])
        ask_volumes = kwargs.get("ask_volumes", [])
        
        if not bid_volumes or not ask_volumes:
            return None
        
        # Calculate order flow imbalance
        bid_sum = sum(bid_volumes[-5:]) if len(bid_volumes) >= 5 else sum(bid_volumes)
        ask_sum = sum(ask_volumes[-5:]) if len(ask_volumes) >= 5 else sum(ask_volumes)
        
        if ask_sum == 0:
            return None
        
        imbalance = bid_sum / ask_sum
        
        if imbalance > self.imbalance_threshold:
            return Signal(
                action="buy",
                confidence=min(0.7, 0.5 + (imbalance - 1) * 0.2),
                strategy=self.name,
                reason=f"Bid imbalance ({imbalance:.2f}x)",
                strength=imbalance / self.imbalance_threshold,
            )
        elif imbalance < 1 / self.imbalance_threshold:
            return Signal(
                action="sell",
                confidence=min(0.7, 0.5 + (1/imbalance - 1) * 0.2),
                strategy=self.name,
                reason=f"Ask imbalance ({1/imbalance:.2f}x)",
                strength=(1/imbalance) / self.imbalance_threshold,
            )
        
        return None


# ============================================================================
# 6. STATISTICAL ARBITRAGE
# ============================================================================

class PairsTrading(TradingStrategy):
    """Trade spread between correlated pairs."""
    
    def __init__(self, entry_z: float = 2.0, exit_z: float = 0.0):
        super().__init__(f"PairsTrade")
        self.entry_z = entry_z
        self.exit_z = exit_z
        self.spread_history: Deque[float] = deque(maxlen=100)
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        prices2 = kwargs.get("prices2", [])
        
        if not prices2 or len(prices) < 20 or len(prices2) < 20:
            return None
        
        # Calculate spread
        spread = prices[-1] - prices2[-1]
        self.spread_history.append(spread)
        
        if len(self.spread_history) < 20:
            return None
        
        # Calculate z-score of spread
        mean_spread = np.mean(self.spread_history)
        std_spread = np.std(self.spread_history)
        
        if std_spread == 0:
            return None
        
        z_score = (spread - mean_spread) / std_spread
        
        # Spread too wide - expect convergence
        if z_score > self.entry_z:
            return Signal(
                action="sell",
                confidence=min(0.8, 0.5 + abs(z_score) / 10),
                strategy=self.name,
                reason=f"Spread wide (z={z_score:.2f})",
                strength=abs(z_score) / self.entry_z,
            )
        elif z_score < -self.entry_z:
            return Signal(
                action="buy",
                confidence=min(0.8, 0.5 + abs(z_score) / 10),
                strategy=self.name,
                reason=f"Spread wide negative (z={z_score:.2f})",
                strength=abs(z_score) / self.entry_z,
            )
        
        return None


class CointegrationReversion(TradingStrategy):
    """Trade cointegrated series reversion."""
    
    def __init__(self, period: int = 50, entry_z: float = 2.0):
        super().__init__(f"CointReversion")
        self.period = period
        self.entry_z = entry_z
        self.spread_history: Deque[float] = deque(maxlen=200)
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        prices2 = kwargs.get("prices2", [])
        
        if not prices2 or len(prices) < self.period or len(prices2) < self.period:
            return None
        
        # Calculate hedge ratio (simplified)
        returns1 = np.diff(np.log(prices[-self.period:]))
        returns2 = np.diff(np.log(prices2[-self.period:]))
        
        if np.std(returns1) == 0:
            return None
        
        hedge_ratio = np.cov(returns1, returns2)[0, 1] / np.var(returns1)
        
        # Calculate spread
        spread = prices[-1] - hedge_ratio * prices2[-1]
        self.spread_history.append(spread)
        
        if len(self.spread_history) < 30:
            return None
        
        # Z-score of spread
        mean_spread = np.mean(self.spread_history)
        std_spread = np.std(self.spread_history)
        
        if std_spread == 0:
            return None
        
        z_score = (spread - mean_spread) / std_spread
        
        if z_score > self.entry_z:
            return Signal(
                action="sell",
                confidence=0.7,
                strategy=self.name,
                reason=f"Cointegration spread wide (z={z_score:.2f})",
                strength=abs(z_score) / self.entry_z,
            )
        elif z_score < -self.entry_z:
            return Signal(
                action="buy",
                confidence=0.7,
                strategy=self.name,
                reason=f"Cointegration spread wide (z={z_score:.2f})",
                strength=abs(z_score) / self.entry_z,
            )
        
        return None


# ============================================================================
# 7. MARKET MAKING STRATEGIES
# ============================================================================

class SimpleMarketMaking(TradingStrategy):
    """Simple market making around fair value."""
    
    def __init__(self, spread_pct: float = 0.001):
        super().__init__(f"MarketMaking")
        self.spread_pct = spread_pct
        self.fair_value: float = 0.0
        self.inventory: float = 0.0
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        if len(prices) < 10:
            return None
        
        # Update fair value (EMA)
        self.fair_value = np.mean(prices[-10:])
        
        current = prices[-1]
        deviation = (current - self.fair_value) / self.fair_value
        
        # Skew quotes based on inventory
        inventory_skew = -self.inventory * 0.0001
        
        # Buy when price is below fair value + skew
        if deviation < -self.spread_pct + inventory_skew:
            return Signal(
                action="buy",
                confidence=0.5,
                strategy=self.name,
                reason=f"Market making buy (dev={deviation:.3%})",
                strength=abs(deviation) / self.spread_pct,
            )
        
        # Sell when price is above fair value + skew
        if deviation > self.spread_pct + inventory_skew:
            return Signal(
                action="sell",
                confidence=0.5,
                strategy=self.name,
                reason=f"Market making sell (dev={deviation:.3%})",
                strength=abs(deviation) / self.spread_pct,
            )
        
        return None


# ============================================================================
# 8. VOLUME PROFILE STRATEGIES
# ============================================================================

class VolumeProfileTrading(TradingStrategy):
    """Trade based on volume profile (POC, VA, etc)."""
    
    def __init__(self, lookback: int = 100, num_bins: int = 20):
        super().__init__(f"VolumeProfile")
        self.lookback = lookback
        self.num_bins = num_bins
    
    def analyze(self, prices: List[float], **kwargs) -> Optional[Signal]:
        volumes = kwargs.get("volumes", [])
        
        if not volumes or len(prices) < self.lookback:
            return None
        
        # Build volume profile
        price_range = max(prices[-self.lookback:]) - min(prices[-self.lookback:])
        if price_range == 0:
            return None
        
        bin_size = price_range / self.num_bins
        min_price = min(prices[-self.lookback:])
        
        profile = np.zeros(self.num_bins)
        
        for i, price in enumerate(prices[-self.lookback:]):
            vol = volumes[-self.lookback + i] if i < len(volumes) else 1
            bin_idx = min(int((price - min_price) / bin_size), self.num_bins - 1)
            profile[bin_idx] += vol
        
        # Find Point of Control (POC)
        poc_idx = np.argmax(profile)
        poc_price = min_price + (poc_idx + 0.5) * bin_size
        
        # Current price relative to POC
        current = prices[-1]
        poc_deviation = (current - poc_price) / poc_price
        
        # Value Area (70% of volume)
        total_volume = np.sum(profile)
        value_area_threshold = total_volume * 0.35
        
        # Find value area high/low
        sorted_bins = np.argsort(profile)[::-1]
        cumulative = 0
        va_bins = []
        
        for idx in sorted_bins:
            cumulative += profile[idx]
            va_bins.append(idx)
            if cumulative >= total_volume * 0.7:
                break
        
        va_high = max(va_bins) * bin_size + min_price + bin_size
        va_low = min(va_bins) * bin_size + min_price
        
        # Trade signals
        if current < va_low:
            # Below value area - buy
            return Signal(
                action="buy",
                confidence=0.65,
                strategy=self.name,
                reason=f"Below value area low (POC={poc_price:.2f})",
                strength=(poc_price - current) / poc_price,
            )
        elif current > va_high:
            # Above value area - sell
            return Signal(
                action="sell",
                confidence=0.65,
                strategy=self.name,
                reason=f"Above value area high (POC={poc_price:.2f})",
                strength=(current - poc_price) / poc_price,
            )
        
        return None


# ============================================================================
# STRATEGY REGISTRY
# ============================================================================

class StrategyRegistry:
    """Registry of all available trading strategies."""
    
    def __init__(self):
        self.strategies: Dict[str, TradingStrategy] = {}
        self._register_all()
    
    def _register_all(self) -> None:
        """Register all strategies."""
        # Trend Following
        self.register(SMACrossover(10, 30))
        self.register(SMACrossover(5, 20))
        self.register(EMACrossover(12, 26))
        self.register(ADXTrendStrength(14, 25))
        self.register(ParabolicSAR())
        
        # Momentum
        self.register(RSIMomentum(14, 70, 30))
        self.register(RSIMomentum(9, 75, 25))
        self.register(MACDMomentum(12, 26, 9))
        self.register(ROCMomentum(10, 0.02))
        self.register(StochasticMomentum(14, 3))
        
        # Mean Reversion
        self.register(BollingerBandReversion(20, 2.0))
        self.register(BollingerBandReversion(10, 1.5))
        self.register(ZScoreReversion(20, 2.0, 0.5))
        self.register(RSIReversion(14))
        
        # Breakout
        self.register(RangeBreakout(20, 0.005))
        self.register(RangeBreakout(50, 0.003))
        self.register(VolumeBreakout(20, 1.5))
        
        # Scalping
        self.register(SpreadScalping(0.001))
        self.register(OrderFlowScalping(1.5))
        
        # Statistical Arbitrage
        self.register(PairsTrading(2.0, 0.0))
        self.register(CointegrationReversion(50, 2.0))
        
        # Market Making
        self.register(SimpleMarketMaking(0.001))
        
        # Volume Profile
        self.register(VolumeProfileTrading(100, 20))
    
    def register(self, strategy: TradingStrategy) -> None:
        """Register a strategy."""
        self.strategies[strategy.name] = strategy
    
    def get_all_signals(self, prices: List[float], **kwargs) -> List[Signal]:
        """Get signals from all strategies."""
        signals = []
        
        for strategy in self.strategies.values():
            if not strategy.enabled:
                continue
            
            signal = strategy.analyze(prices, **kwargs)
            if signal:
                signals.append(signal)
                strategy.signals_generated += 1
        
        return signals
    
    def get_best_strategy(self) -> Optional[TradingStrategy]:
        """Get the best performing strategy."""
        if not self.strategies:
            return None
        
        best = max(self.strategies.values(), key=lambda s: s.get_score())
        return best
    
    def get_strategy_stats(self) -> Dict[str, Dict[str, Any]]:
        """Get stats for all strategies."""
        stats = {}
        for name, strategy in self.strategies.items():
            stats[name] = {
                "enabled": strategy.enabled,
                "signals": strategy.signals_generated,
                "win_rate": strategy.get_win_rate(),
                "total_pnl": strategy.total_pnl,
                "score": strategy.get_score(),
            }
        return stats


# Singleton
_registry: Optional[StrategyRegistry] = None


def get_strategy_registry() -> StrategyRegistry:
    """Get or create singleton registry."""
    global _registry
    if _registry is None:
        _registry = StrategyRegistry()
    return _registry


def reset_registry() -> None:
    """Reset singleton."""
    global _registry
    _registry = None
