from __future__ import annotations

from enum import Enum
from typing import Any, Dict


class ReasonCode(str, Enum):
    """Canonical reason codes for trade gate and execution decisions."""

    ALLOWED = "ALLOWED"
    PRE_EXEC = "PRE_EXEC"
    PRE_PUBLISH = "PRE_PUBLISH"
    POST_EXEC = "POST_EXEC"
    DUPLICATE_SIGNAL = "DUPLICATE_SIGNAL"
    RECONCILIATION_HALT = "RECONCILIATION_HALT"
    MIN_CONFIDENCE = "MIN_CONFIDENCE"
    STRATEGY_COOLDOWN = "STRATEGY_COOLDOWN"
    MAX_POSITION_SIZE = "MAX_POSITION_SIZE"
    PORTFOLIO_VAR_REJECT = "PORTFOLIO_VAR_REJECT"
    PORTFOLIO_CVAR_REJECT = "PORTFOLIO_CVAR_REJECT"
    CLUSTER_DRAWDOWN_REJECT = "CLUSTER_DRAWDOWN_REJECT"
    VOL_LIQUIDITY_CAP_REJECT = "VOL_LIQUIDITY_CAP_REJECT"
    IS_GATE_REJECT = "IS_GATE_REJECT"
    EDGE_COST_REJECT = "EDGE_COST_REJECT"
    TRADE_LIMIT_REACHED = "TRADE_LIMIT_REACHED"
    SYMBOL_COOLDOWN = "SYMBOL_COOLDOWN"
    FEE_BUDGET_EXCEEDED = "FEE_BUDGET_EXCEEDED"
    LOSS_STREAK_COOLDOWN = "LOSS_STREAK_COOLDOWN"
    PRE_TRADE_RISK_BLOCK = "PRE_TRADE_RISK_BLOCK"
    SPREAD_REJECT = "SPREAD_REJECT"
    EXCHANGE_UNAVAILABLE = "EXCHANGE_UNAVAILABLE"
    TICKER_UNAVAILABLE = "TICKER_UNAVAILABLE"
    EXCHANGE_HEARTBEAT_STALE = "EXCHANGE_HEARTBEAT_STALE"
    MARKET_DATA_STALE = "MARKET_DATA_STALE"
    CLOCK_SKEW_EXCEEDED = "CLOCK_SKEW_EXCEEDED"
    FAIL_CLOSED_RUNTIME = "FAIL_CLOSED_RUNTIME"
    ORDER_FAILED = "ORDER_FAILED"
    ORDER_AMBIGUOUS = "ORDER_AMBIGUOUS"
    RECONCILIATION_FREEZE = "RECONCILIATION_FREEZE"
    OPERATOR_ACK_REQUIRED = "OPERATOR_ACK_REQUIRED"
    SLIPPAGE_GUARDRAIL = "SLIPPAGE_GUARDRAIL"
    INTENT_ALREADY_FINAL = "INTENT_ALREADY_FINAL"
    INTENT_PENDING_NO_RESEND = "INTENT_PENDING_NO_RESEND"
    RECON_REQUIRED_LOCK = "RECON_REQUIRED_LOCK"
    RECON_RECOVERY_RETRY = "RECON_RECOVERY_RETRY"
    RECON_RECOVERY_CLEARED = "RECON_RECOVERY_CLEARED"
    RECON_RECOVERY_HALT_REQUIRED = "RECON_RECOVERY_HALT_REQUIRED"
    RECON_RECOVERY_OPERATOR_REVIEW = "RECON_RECOVERY_OPERATOR_REVIEW"


def normalize_details(details: Dict[str, Any] | None) -> Dict[str, Any]:
    if not isinstance(details, dict):
        return {}
    out: Dict[str, Any] = {}
    for k, v in details.items():
        if isinstance(v, (str, int, float, bool)) or v is None:
            out[str(k)] = v
        else:
            out[str(k)] = str(v)
    return out
