"""
Code Generator — writes new Python strategy files based on observed patterns.

This is the heart of true self-modifying ARGUS. It takes patterns observed
in market data + trade outcomes and emits Python source code that implements
new trading strategies.

SAFETY DESIGN:
  - Uses TEMPLATES not freeform generation (no LLM hallucination)
  - All generated code goes to generated_strategies/candidates/
  - Whitelisted operations only (no I/O, no network, no eval)
  - Validated by code_review_gate before being moved to active/
  - Versioned in git for rollback
  - Cannot edit existing ARGUS source files

The generator produces strategies in 5 templates:
  1. THRESHOLD       — single indicator vs threshold
  2. CONFLUENCE      — multiple conditions AND-ed together
  3. REGIME_SPECIFIC — only fires in matching regime
  4. CROSSOVER       — fast indicator crosses slow
  5. PATTERN_MATCH   — recognises a sequence of features
"""
from __future__ import annotations

import ast
import hashlib
import logging
import re
import textwrap
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


class StrategyTemplate(str, Enum):
    THRESHOLD = "threshold"
    CONFLUENCE = "confluence"
    REGIME_SPECIFIC = "regime_specific"
    CROSSOVER = "crossover"
    PATTERN_MATCH = "pattern_match"


@dataclass
class GenerationContext:
    """Context that drives code generation — observed patterns, fitness, etc."""
    pattern_id: str
    observation_count: int
    win_rate: float
    avg_pnl_aud: float
    sharpe: float
    target_regime: str
    indicators_used: List[str] = field(default_factory=list)
    features: Dict[str, Any] = field(default_factory=dict)
    description: str = ""


@dataclass
class GeneratedStrategy:
    """A generated strategy file with metadata."""
    name: str
    template: StrategyTemplate
    file_path: Path
    source_code: str
    context: GenerationContext
    code_hash: str
    timestamp: float = field(default_factory=time.time)
    validated: bool = False
    deployed: bool = False
    retired: bool = False
    retire_reason: str = ""


# ─────────────────────────────────────────────────────────────────────────────
# Templates — strict, parameterised, ast-validated
# ─────────────────────────────────────────────────────────────────────────────

THRESHOLD_TEMPLATE = '''"""
{description}

Auto-generated by ARGUS code_generator at {timestamp}.
Pattern: {pattern_id}
Observations: {observation_count}
Historical win rate: {win_rate:.2%}
Historical avg P&L: ${avg_pnl_aud:.2f}
Historical Sharpe: {sharpe:.3f}

DO NOT EDIT MANUALLY — managed by code_evolution_engine.
"""
from __future__ import annotations

from generated_strategies import BaseGeneratedStrategy


class GeneratedStrategy_{class_suffix}(BaseGeneratedStrategy):
    """Threshold-based strategy on {indicator}."""

    name = "{name}"
    version = 1
    generation_id = "{generation_id}"
    target_regime = "{target_regime}"
    description = "{description}"

    INDICATOR = "{indicator}"
    THRESHOLD = {threshold}
    DIRECTION = "{direction}"
    CONFIDENCE_BASE = {confidence_base}

    def evaluate(self, market_state: dict) -> dict:
        if not isinstance(market_state, dict):
            return {{"action": "HOLD", "confidence": 0.0, "reasoning": "invalid_state"}}
        if self.target_regime != "ANY":
            if market_state.get("regime") != self.target_regime:
                return {{"action": "HOLD", "confidence": 0.0, "reasoning": "regime_mismatch"}}
        value = market_state.get(self.INDICATOR)
        if value is None:
            return {{"action": "HOLD", "confidence": 0.0, "reasoning": "indicator_missing"}}
        try:
            value = float(value)
        except (TypeError, ValueError):
            return {{"action": "HOLD", "confidence": 0.0, "reasoning": "indicator_invalid"}}
        if self.DIRECTION == "above" and value > self.THRESHOLD:
            return {{
                "action": "BUY",
                "confidence": self.CONFIDENCE_BASE,
                "reasoning": f"{{self.INDICATOR}}={{value:.4f}} > {{self.THRESHOLD}}",
            }}
        if self.DIRECTION == "below" and value < self.THRESHOLD:
            return {{
                "action": "SELL",
                "confidence": self.CONFIDENCE_BASE,
                "reasoning": f"{{self.INDICATOR}}={{value:.4f}} < {{self.THRESHOLD}}",
            }}
        return {{"action": "HOLD", "confidence": 0.0, "reasoning": "no_signal"}}
'''

CONFLUENCE_TEMPLATE = '''"""
{description}

Auto-generated by ARGUS code_generator at {timestamp}.
Pattern: {pattern_id}
Observations: {observation_count}
Historical win rate: {win_rate:.2%}
Historical avg P&L: ${avg_pnl_aud:.2f}
Historical Sharpe: {sharpe:.3f}

DO NOT EDIT MANUALLY — managed by code_evolution_engine.
"""
from __future__ import annotations

from generated_strategies import BaseGeneratedStrategy


class GeneratedStrategy_{class_suffix}(BaseGeneratedStrategy):
    """Confluence strategy requiring multiple conditions."""

    name = "{name}"
    version = 1
    generation_id = "{generation_id}"
    target_regime = "{target_regime}"
    description = "{description}"

    CONDITIONS = {conditions_repr}
    ACTION = "{action}"
    CONFIDENCE_BASE = {confidence_base}

    def evaluate(self, market_state: dict) -> dict:
        if not isinstance(market_state, dict):
            return {{"action": "HOLD", "confidence": 0.0, "reasoning": "invalid_state"}}
        if self.target_regime != "ANY":
            if market_state.get("regime") != self.target_regime:
                return {{"action": "HOLD", "confidence": 0.0, "reasoning": "regime_mismatch"}}
        matched = 0
        total = len(self.CONDITIONS)
        for cond in self.CONDITIONS:
            field = cond["field"]
            op = cond["op"]
            target = cond["value"]
            value = market_state.get(field)
            if value is None:
                continue
            try:
                value = float(value)
                target = float(target)
            except (TypeError, ValueError):
                continue
            if op == "gt" and value > target:
                matched += 1
            elif op == "lt" and value < target:
                matched += 1
            elif op == "ge" and value >= target:
                matched += 1
            elif op == "le" and value <= target:
                matched += 1
            elif op == "eq" and value == target:
                matched += 1
        if matched == total and total > 0:
            return {{
                "action": self.ACTION,
                "confidence": self.CONFIDENCE_BASE,
                "reasoning": f"all {{total}} conditions met",
            }}
        return {{
            "action": "HOLD",
            "confidence": 0.0,
            "reasoning": f"{{matched}}/{{total}} conditions met",
        }}
'''

CROSSOVER_TEMPLATE = '''"""
{description}

Auto-generated by ARGUS code_generator at {timestamp}.
Pattern: {pattern_id}
Observations: {observation_count}
Historical win rate: {win_rate:.2%}
Historical avg P&L: ${avg_pnl_aud:.2f}
Historical Sharpe: {sharpe:.3f}

DO NOT EDIT MANUALLY — managed by code_evolution_engine.
"""
from __future__ import annotations

from generated_strategies import BaseGeneratedStrategy


class GeneratedStrategy_{class_suffix}(BaseGeneratedStrategy):
    """Crossover strategy: fast indicator vs slow indicator."""

    name = "{name}"
    version = 1
    generation_id = "{generation_id}"
    target_regime = "{target_regime}"
    description = "{description}"

    FAST_INDICATOR = "{fast_indicator}"
    SLOW_INDICATOR = "{slow_indicator}"
    BUY_ON = "{buy_on}"
    CONFIDENCE_BASE = {confidence_base}

    def evaluate(self, market_state: dict) -> dict:
        if not isinstance(market_state, dict):
            return {{"action": "HOLD", "confidence": 0.0, "reasoning": "invalid_state"}}
        if self.target_regime != "ANY":
            if market_state.get("regime") != self.target_regime:
                return {{"action": "HOLD", "confidence": 0.0, "reasoning": "regime_mismatch"}}
        fast = market_state.get(self.FAST_INDICATOR)
        slow = market_state.get(self.SLOW_INDICATOR)
        if fast is None or slow is None:
            return {{"action": "HOLD", "confidence": 0.0, "reasoning": "indicators_missing"}}
        try:
            fast = float(fast)
            slow = float(slow)
        except (TypeError, ValueError):
            return {{"action": "HOLD", "confidence": 0.0, "reasoning": "indicators_invalid"}}
        if self.BUY_ON == "above" and fast > slow:
            return {{
                "action": "BUY",
                "confidence": self.CONFIDENCE_BASE,
                "reasoning": f"{{self.FAST_INDICATOR}}({{fast:.4f}}) > {{self.SLOW_INDICATOR}}({{slow:.4f}})",
            }}
        if self.BUY_ON == "below" and fast < slow:
            return {{
                "action": "BUY",
                "confidence": self.CONFIDENCE_BASE,
                "reasoning": f"{{self.FAST_INDICATOR}}({{fast:.4f}}) < {{self.SLOW_INDICATOR}}({{slow:.4f}})",
            }}
        return {{"action": "HOLD", "confidence": 0.0, "reasoning": "no_crossover"}}
'''


# ─────────────────────────────────────────────────────────────────────────────
# Code Generator
# ─────────────────────────────────────────────────────────────────────────────

class CodeGenerator:
    """
    Generates trading strategy Python files from observed patterns.

    Usage::

        gen = CodeGenerator(output_dir="generated_strategies/candidates")

        ctx = GenerationContext(
            pattern_id="rsi30_btc_trending",
            observation_count=150,
            win_rate=0.62,
            avg_pnl_aud=8.5,
            sharpe=1.2,
            target_regime="TRENDING_UP",
        )

        strategy = gen.generate_threshold_strategy(
            ctx,
            indicator="rsi",
            threshold=30.0,
            direction="below",
        )
        # File written to candidates/, ready for review
    """

    def __init__(
        self,
        output_dir: str = "generated_strategies/candidates",
        max_generations: int = 10_000,
    ) -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.max_generations = max_generations
        self._generation_count = 0
        self._stats: Dict[str, int] = {
            "threshold": 0,
            "confluence": 0,
            "crossover": 0,
            "errors": 0,
        }
        logger.info("CodeGenerator: initialized at %s", self.output_dir)

    def generate_threshold_strategy(
        self,
        context: GenerationContext,
        indicator: str,
        threshold: float,
        direction: str = "above",
        confidence_base: float = 0.6,
    ) -> Optional[GeneratedStrategy]:
        """Generate a single-indicator threshold strategy."""
        self._generation_count += 1
        if self._generation_count > self.max_generations:
            logger.warning("CodeGenerator: max generations reached")
            return None

        # Sanitize inputs
        indicator = self._sanitize_identifier(indicator)
        if not indicator:
            self._stats["errors"] += 1
            return None
        if direction not in ("above", "below"):
            self._stats["errors"] += 1
            return None

        timestamp = datetime.now(tz=timezone.utc).strftime("%Y%m%d_%H%M%S")
        suffix = self._generate_suffix(context.pattern_id, "threshold")
        name = f"threshold_{indicator}_{direction}_{suffix}"
        class_suffix = re.sub(r'\W+', '_', f"{indicator}_{direction}_{suffix}")

        source = THRESHOLD_TEMPLATE.format(
            description=self._sanitize_string(context.description or "Threshold strategy"),
            timestamp=timestamp,
            pattern_id=self._sanitize_string(context.pattern_id),
            observation_count=context.observation_count,
            win_rate=context.win_rate,
            avg_pnl_aud=context.avg_pnl_aud,
            sharpe=context.sharpe,
            class_suffix=class_suffix,
            name=name,
            generation_id=suffix,
            target_regime=self._sanitize_string(context.target_regime or "ANY"),
            indicator=indicator,
            threshold=float(threshold),
            direction=direction,
            confidence_base=float(max(0.0, min(confidence_base, 1.0))),
        )

        # Validate by parsing as AST
        if not self._validate_syntax(source):
            self._stats["errors"] += 1
            logger.warning("CodeGenerator: syntax validation failed for %s", name)
            return None

        file_path = self.output_dir / f"{name}.py"
        file_path.write_text(source, encoding="utf-8")

        code_hash = hashlib.sha256(source.encode()).hexdigest()[:16]
        self._stats["threshold"] += 1

        strategy = GeneratedStrategy(
            name=name,
            template=StrategyTemplate.THRESHOLD,
            file_path=file_path,
            source_code=source,
            context=context,
            code_hash=code_hash,
        )
        logger.info("CodeGenerator: emitted %s (hash=%s)", name, code_hash)
        return strategy

    def generate_confluence_strategy(
        self,
        context: GenerationContext,
        conditions: List[Dict[str, Any]],
        action: str = "BUY",
        confidence_base: float = 0.7,
    ) -> Optional[GeneratedStrategy]:
        """Generate a multi-condition confluence strategy."""
        self._generation_count += 1

        # Validate conditions
        valid_ops = {"gt", "lt", "ge", "le", "eq"}
        validated_conditions: List[Dict[str, Any]] = []
        for c in conditions:
            field = self._sanitize_identifier(str(c.get("field", "")))
            op = str(c.get("op", "")).lower()
            value = c.get("value")
            if not field or op not in valid_ops or value is None:
                continue
            try:
                value = float(value)
            except (TypeError, ValueError):
                continue
            validated_conditions.append({"field": field, "op": op, "value": value})

        if len(validated_conditions) < 2:
            self._stats["errors"] += 1
            return None

        if action not in ("BUY", "SELL"):
            self._stats["errors"] += 1
            return None

        timestamp = datetime.now(tz=timezone.utc).strftime("%Y%m%d_%H%M%S")
        suffix = self._generate_suffix(context.pattern_id, "confluence")
        name = f"confluence_{action.lower()}_{suffix}"
        class_suffix = f"{action.lower()}_{suffix}"

        source = CONFLUENCE_TEMPLATE.format(
            description=self._sanitize_string(context.description or "Confluence strategy"),
            timestamp=timestamp,
            pattern_id=self._sanitize_string(context.pattern_id),
            observation_count=context.observation_count,
            win_rate=context.win_rate,
            avg_pnl_aud=context.avg_pnl_aud,
            sharpe=context.sharpe,
            class_suffix=class_suffix,
            name=name,
            generation_id=suffix,
            target_regime=self._sanitize_string(context.target_regime or "ANY"),
            conditions_repr=repr(validated_conditions),
            action=action,
            confidence_base=float(max(0.0, min(confidence_base, 1.0))),
        )

        if not self._validate_syntax(source):
            self._stats["errors"] += 1
            return None

        file_path = self.output_dir / f"{name}.py"
        file_path.write_text(source, encoding="utf-8")

        code_hash = hashlib.sha256(source.encode()).hexdigest()[:16]
        self._stats["confluence"] += 1

        strategy = GeneratedStrategy(
            name=name,
            template=StrategyTemplate.CONFLUENCE,
            file_path=file_path,
            source_code=source,
            context=context,
            code_hash=code_hash,
        )
        logger.info("CodeGenerator: emitted %s (hash=%s)", name, code_hash)
        return strategy

    def generate_crossover_strategy(
        self,
        context: GenerationContext,
        fast_indicator: str,
        slow_indicator: str,
        buy_on: str = "above",
        confidence_base: float = 0.65,
    ) -> Optional[GeneratedStrategy]:
        """Generate a fast/slow crossover strategy."""
        self._generation_count += 1

        fast = self._sanitize_identifier(fast_indicator)
        slow = self._sanitize_identifier(slow_indicator)
        if not fast or not slow or fast == slow:
            self._stats["errors"] += 1
            return None
        if buy_on not in ("above", "below"):
            self._stats["errors"] += 1
            return None

        timestamp = datetime.now(tz=timezone.utc).strftime("%Y%m%d_%H%M%S")
        suffix = self._generate_suffix(context.pattern_id, "crossover")
        name = f"crossover_{fast}_{slow}_{suffix}"
        class_suffix = re.sub(r'\W+', '_', f"{fast}_{slow}_{suffix}")

        source = CROSSOVER_TEMPLATE.format(
            description=self._sanitize_string(context.description or "Crossover strategy"),
            timestamp=timestamp,
            pattern_id=self._sanitize_string(context.pattern_id),
            observation_count=context.observation_count,
            win_rate=context.win_rate,
            avg_pnl_aud=context.avg_pnl_aud,
            sharpe=context.sharpe,
            class_suffix=class_suffix,
            name=name,
            generation_id=suffix,
            target_regime=self._sanitize_string(context.target_regime or "ANY"),
            fast_indicator=fast,
            slow_indicator=slow,
            buy_on=buy_on,
            confidence_base=float(max(0.0, min(confidence_base, 1.0))),
        )

        if not self._validate_syntax(source):
            self._stats["errors"] += 1
            return None

        file_path = self.output_dir / f"{name}.py"
        file_path.write_text(source, encoding="utf-8")

        code_hash = hashlib.sha256(source.encode()).hexdigest()[:16]
        self._stats["crossover"] += 1

        strategy = GeneratedStrategy(
            name=name,
            template=StrategyTemplate.CROSSOVER,
            file_path=file_path,
            source_code=source,
            context=context,
            code_hash=code_hash,
        )
        logger.info("CodeGenerator: emitted %s (hash=%s)", name, code_hash)
        return strategy

    @staticmethod
    def _sanitize_identifier(name: str) -> str:
        """Sanitize a string to be a valid Python identifier."""
        if not name:
            return ""
        cleaned = re.sub(r'\W+', '_', str(name).strip().lower())
        cleaned = re.sub(r'^[^a-z_]+', '', cleaned)
        if not cleaned or not cleaned[0].isalpha() and cleaned[0] != '_':
            return ""
        # Reject pure-underscore or empty after cleanup
        if not any(c.isalpha() for c in cleaned):
            return ""
        return cleaned[:50]

    @staticmethod
    def _sanitize_string(s: str) -> str:
        """Sanitize a string for safe interpolation in Python code."""
        if not s:
            return ""
        # Strip control characters and limit length
        cleaned = re.sub(r'[\x00-\x1f\x7f]', '', str(s))
        # Escape quotes and backslashes
        cleaned = cleaned.replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'")
        return cleaned[:500]

    @staticmethod
    def _generate_suffix(pattern_id: str, template_type: str) -> str:
        """Generate a unique suffix for the strategy name."""
        ts_ms = int(time.time() * 1000)
        seed = f"{pattern_id}_{template_type}_{ts_ms}"
        h = hashlib.sha256(seed.encode()).hexdigest()[:8]
        return h

    @staticmethod
    def _validate_syntax(source: str) -> bool:
        """Validate that the generated source is syntactically valid Python."""
        try:
            ast.parse(source)
            return True
        except SyntaxError as exc:
            logger.warning("CodeGenerator: AST parse failed: %s", exc)
            return False

    def snapshot(self) -> Dict[str, Any]:
        return {
            "output_dir": str(self.output_dir),
            "generation_count": self._generation_count,
            "max_generations": self.max_generations,
            "stats": dict(self._stats),
        }
