"""
Argus Trading System - Core Type Definitions
============================================

Canonical shared types for the entire trading system. These are lightweight,
dependency-free dataclasses that can be imported by any module without
circular import issues.

Design Principles:
- Immutable where possible (frozen dataclasses)
- Type-safe with explicit annotations
- Serialization-friendly (JSON-compatible)
- No external dependencies beyond stdlib + numpy/pandas
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


# =============================================================================
# Enums
# =============================================================================

class Side(str, Enum):
    """Order/position side."""
    BUY = "buy"
    SELL = "sell"

    @classmethod
    def from_string(cls, s: str) -> "Side":
        s_lower = s.lower().strip()
        if s_lower in ("buy", "long"):
            return cls.BUY
        if s_lower in ("sell", "short"):
            return cls.SELL
        raise ValueError(f"Invalid side: {s}")


class OrderType(str, Enum):
    """Order types supported by the system."""
    MARKET = "market"
    LIMIT = "limit"
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    STOP_LIMIT = "stop_limit"


class OrderStatus(str, Enum):
    """Order lifecycle status."""
    PENDING = "pending"
    OPEN = "open"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class SignalAction(str, Enum):
    """Trading signal actions."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE = "CLOSE"


class MarketRegime(str, Enum):
    """Market regime classifications."""
    TREND_UP = "trend_up"
    TREND_DOWN = "trend_down"
    RANGE = "range"
    HIGH_VOL = "high_vol"
    LOW_VOL = "low_vol"
    UNKNOWN = "unknown"


class RiskLevel(str, Enum):
    """Risk assessment levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ExecutionAlgo(str, Enum):
    """Execution algorithm types."""
    MARKET = "market"
    LIMIT = "limit"
    TWAP = "twap"
    VWAP = "vwap"
    ICEBERG = "iceberg"
    SMART = "smart"


# =============================================================================
# Core Trading Types
# =============================================================================

@dataclass(frozen=True)
class Signal:
    """
    Trading signal generated by a strategy.

    Immutable to ensure signal integrity through the processing pipeline.
    """
    symbol: str
    action: SignalAction
    confidence: float  # 0.0 - 1.0
    strength: float    # 0.0 - 1.0, signal magnitude
    entry_price: float
    signal_id: str = ""  # Unique identifier for tracking
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    strategy_name: str = ""
    reasoning: str = ""
    regime: MarketRegime = MarketRegime.UNKNOWN
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        # Validate confidence and strength are in valid range
        object.__setattr__(self, 'confidence', max(0.0, min(1.0, self.confidence)))
        object.__setattr__(self, 'strength', max(0.0, min(1.0, self.strength)))

    @property
    def is_entry(self) -> bool:
        """Check if this is an entry signal (BUY or SELL)."""
        return self.action in (SignalAction.BUY, SignalAction.SELL)

    @property
    def is_exit(self) -> bool:
        """Check if this is an exit signal (CLOSE)."""
        return self.action == SignalAction.CLOSE

    @property
    def score(self) -> float:
        """Combined confidence * strength score for ranking."""
        return self.confidence * self.strength

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "symbol": self.symbol,
            "action": self.action.value,
            "confidence": self.confidence,
            "strength": self.strength,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "strategy_name": self.strategy_name,
            "reasoning": self.reasoning,
            "regime": self.regime.value,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
        }


@dataclass
class Position:
    """
    Current position state.

    Mutable to track real-time position updates.
    """
    symbol: str
    side: Side
    quantity: float
    entry_price: float
    entry_time: datetime
    current_price: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    strategy_name: str = ""
    position_id: str = ""

    @property
    def notional_value(self) -> float:
        """Current position value."""
        return self.quantity * self.current_price

    @property
    def entry_value(self) -> float:
        """Original position value."""
        return self.quantity * self.entry_price

    @property
    def unrealized_pnl(self) -> float:
        """Unrealized P&L in quote currency."""
        if self.side == Side.BUY:
            return (self.current_price - self.entry_price) * self.quantity
        else:
            return (self.entry_price - self.current_price) * self.quantity

    @property
    def unrealized_pnl_pct(self) -> float:
        """Unrealized P&L as percentage."""
        if self.entry_value == 0:
            return 0.0
        return (self.unrealized_pnl / self.entry_value) * 100.0

    @property
    def is_profitable(self) -> bool:
        """Check if position is currently profitable."""
        return self.unrealized_pnl > 0

    def should_stop_out(self) -> bool:
        """Check if stop loss has been triggered."""
        if self.stop_loss is None:
            return False
        if self.side == Side.BUY:
            return self.current_price <= self.stop_loss
        else:
            return self.current_price >= self.stop_loss

    def should_take_profit(self) -> bool:
        """Check if take profit has been triggered."""
        if self.take_profit is None:
            return False
        if self.side == Side.BUY:
            return self.current_price >= self.take_profit
        else:
            return self.current_price <= self.take_profit


@dataclass(frozen=True)
class OrderRequest:
    """
    Order request to be submitted to an exchange.

    Immutable to ensure order parameters don't change during processing.
    """
    symbol: str
    side: Side
    order_type: OrderType
    quantity: float
    price: Optional[float] = None  # For limit orders
    stop_price: Optional[float] = None  # For stop orders
    client_order_id: str = ""
    time_in_force: str = "GTC"  # GTC, IOC, FOK
    reduce_only: bool = False
    post_only: bool = False
    execution_algo: ExecutionAlgo = ExecutionAlgo.MARKET
    algo_params: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary for exchange submission."""
        return {
            "symbol": self.symbol,
            "side": self.side.value,
            "type": self.order_type.value,
            "quantity": self.quantity,
            "price": self.price,
            "stop_price": self.stop_price,
            "client_order_id": self.client_order_id,
            "time_in_force": self.time_in_force,
            "reduce_only": self.reduce_only,
            "post_only": self.post_only,
        }


@dataclass
class OrderResult:
    """
    Result of an order execution.
    """
    order_id: str
    client_order_id: str
    symbol: str
    side: Side
    order_type: OrderType
    status: OrderStatus
    requested_quantity: float
    filled_quantity: float
    remaining_quantity: float
    average_price: Optional[float]
    fees: float = 0.0
    fee_currency: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)
    exchange: str = ""
    raw_response: Dict[str, Any] = field(default_factory=dict)
    error_message: str = ""

    @property
    def is_filled(self) -> bool:
        """Check if order is fully filled."""
        return self.status == OrderStatus.FILLED

    @property
    def is_partial(self) -> bool:
        """Check if order is partially filled."""
        return self.status == OrderStatus.PARTIALLY_FILLED

    @property
    def fill_rate(self) -> float:
        """Percentage of order filled."""
        if self.requested_quantity == 0:
            return 0.0
        return (self.filled_quantity / self.requested_quantity) * 100.0


@dataclass(frozen=True)
class Trade:
    """
    Completed trade record for ledger.
    """
    trade_id: str
    order_id: str
    symbol: str
    side: Side
    quantity: float
    price: float
    fees: float
    fee_currency: str
    timestamp: datetime
    exchange: str
    strategy_name: str = ""
    pnl: Optional[float] = None  # Set when position is closed
    pnl_pct: Optional[float] = None


# =============================================================================
# Market Data Types
# =============================================================================

@dataclass(frozen=True)
class Ticker:
    """
    Real-time ticker data.
    """
    symbol: str
    bid: float
    ask: float
    last: float
    volume_24h: float
    timestamp: datetime
    exchange: str

    @property
    def mid(self) -> float:
        """Mid-market price."""
        return (self.bid + self.ask) / 2.0

    @property
    def spread(self) -> float:
        """Bid-ask spread in quote currency."""
        return self.ask - self.bid

    @property
    def spread_bps(self) -> float:
        """Bid-ask spread in basis points."""
        if self.mid == 0:
            return 0.0
        return (self.spread / self.mid) * 10000.0


@dataclass(frozen=True)
class OHLCV:
    """
    Single OHLCV candle.
    """
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

    @property
    def range(self) -> float:
        """High - Low range."""
        return self.high - self.low

    @property
    def body(self) -> float:
        """Candle body size (absolute)."""
        return abs(self.close - self.open)

    @property
    def is_bullish(self) -> bool:
        """Check if candle is bullish (close > open)."""
        return self.close > self.open


@dataclass(frozen=True)
class OrderBookLevel:
    """Single level in the order book."""
    price: float
    quantity: float


@dataclass
class OrderBook:
    """
    Order book snapshot.
    """
    symbol: str
    bids: List[OrderBookLevel]
    asks: List[OrderBookLevel]
    timestamp: datetime
    exchange: str

    @property
    def best_bid(self) -> Optional[float]:
        """Best (highest) bid price."""
        return self.bids[0].price if self.bids else None

    @property
    def best_ask(self) -> Optional[float]:
        """Best (lowest) ask price."""
        return self.asks[0].price if self.asks else None

    @property
    def mid_price(self) -> Optional[float]:
        """Mid-market price."""
        if self.best_bid is None or self.best_ask is None:
            return None
        return (self.best_bid + self.best_ask) / 2.0

    @property
    def spread(self) -> Optional[float]:
        """Bid-ask spread."""
        if self.best_bid is None or self.best_ask is None:
            return None
        return self.best_ask - self.best_bid

    def bid_depth(self, levels: int = 5) -> float:
        """Total quantity in top N bid levels."""
        return sum(level.quantity for level in self.bids[:levels])

    def ask_depth(self, levels: int = 5) -> float:
        """Total quantity in top N ask levels."""
        return sum(level.quantity for level in self.asks[:levels])

    def imbalance(self, levels: int = 5) -> float:
        """Order book imbalance (-1 to 1). Positive = more bids."""
        bid_qty = self.bid_depth(levels)
        ask_qty = self.ask_depth(levels)
        total = bid_qty + ask_qty
        if total == 0:
            return 0.0
        return (bid_qty - ask_qty) / total


# =============================================================================
# Risk Types
# =============================================================================

@dataclass(frozen=True)
class RiskMetrics:
    """
    Current risk metrics snapshot.
    """
    var_95: float  # 95% Value at Risk
    var_99: float  # 99% Value at Risk
    cvar_95: float  # Conditional VaR (Expected Shortfall)
    drawdown: float  # Current drawdown
    max_drawdown: float  # Maximum drawdown
    sharpe_ratio: float
    sortino_ratio: float
    current_capital: float
    total_exposure: float
    leverage: float
    daily_pnl: float
    daily_return_pct: float
    risk_level: RiskLevel
    circuit_breaker_active: bool
    consecutive_losses: int


@dataclass(frozen=True)
class PositionSizeResult:
    """
    Position sizing calculation result.
    """
    quantity: float
    notional_aud: float
    risk_amount: float
    risk_pct: float
    method: str  # kelly, volatility_adjusted, fixed_fractional
    reasoning: str = ""


@dataclass(frozen=True)
class RiskCheck:
    """
    Result of a risk check.
    """
    approved: bool
    reason: str = ""
    adjusted_size: Optional[float] = None
    risk_score: float = 0.0
    warnings: List[str] = field(default_factory=list)


# =============================================================================
# Regime Types
# =============================================================================

@dataclass(frozen=True)
class RegimeSnapshot:
    """
    Market regime detection result.
    """
    regime: MarketRegime
    trend_score: float  # -1 (bearish) to 1 (bullish)
    volatility: float   # Annualized volatility
    volatility_percentile: float  # 0-100
    sentiment_score: float  # -1 (fear) to 1 (greed)
    confidence: float  # Regime detection confidence
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def is_trending(self) -> bool:
        """Check if market is trending."""
        return self.regime in (MarketRegime.TREND_UP, MarketRegime.TREND_DOWN)

    @property
    def is_ranging(self) -> bool:
        """Check if market is ranging."""
        return self.regime == MarketRegime.RANGE

    @property
    def is_volatile(self) -> bool:
        """Check if market is highly volatile."""
        return self.regime == MarketRegime.HIGH_VOL


# =============================================================================
# Configuration Types
# =============================================================================

@dataclass
class TradingConfig:
    """
    Trading system configuration.
    """
    # Capital
    initial_capital_aud: float = 1000.0
    max_position_pct: float = 0.10  # Max 10% per position

    # Risk limits
    max_daily_loss_pct: float = 0.05  # 5% daily loss limit
    max_drawdown_pct: float = 0.15    # 15% max drawdown
    max_consecutive_losses: int = 5

    # Execution
    default_slippage_bps: float = 5.0
    default_commission_pct: float = 0.26  # Kraken taker fee

    # Strategy
    min_signal_confidence: float = 0.6
    min_signal_strength: float = 0.3

    # Symbols
    symbols: List[str] = field(default_factory=lambda: ["BTC/AUD", "ETH/AUD"])

    # Exchange
    exchange: str = "kraken"
    dry_run: bool = True


# =============================================================================
# Backward Compatibility
# =============================================================================

# Alias for legacy code compatibility
TradingSignal = Signal
