# pyright: reportMissingImports=false
"""
LLM Trading Planner for Argus Trading.

This module implements LLM-based planning for trading decisions,
providing reasoning and action sequences.
"""

from __future__ import annotations

import logging
import random
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
from numpy.typing import NDArray

logger = logging.getLogger(__name__)


class PlanType(Enum):
    """Types of trading plans."""
    CONSERVATIVE = auto()
    BALANCED = auto()
    AGGRESSIVE = auto()
    HEDGING = auto()


@dataclass
class TradingPlan:
    """A trading plan generated by LLM."""
    plan_type: PlanType
    action_sequence: List[Dict[str, Any]]
    reasoning: str
    risk_assessment: str
    expected_outcome: str
    confidence: float
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PlannerConfig:
    """Configuration for LLM trading planner."""
    plan_types: List[PlanType] = field(default_factory=lambda: list(PlanType))
    max_actions: int = 5
    risk_tolerance: float = 0.5
    reasoning_depth: str = "detailed"  # brief, detailed, comprehensive


class LLMTradingPlanner:
    """LLM-based trading planner."""

    def __init__(self, config: Optional[PlannerConfig] = None):
        """Initialize the LLM trading planner."""
        self.config = config or PlannerConfig()
        self.planning_history: List[TradingPlan] = []
        self.templates = self._load_templates()

    def _load_templates(self) -> Dict[str, str]:
        """Load planning templates."""
        return {
            "analysis": """
Analyze the current market conditions:
- Price trend: {trend}
- Volatility: {volatility}
- Volume: {volume}
- Market sentiment: {sentiment}

Based on this analysis, recommend trading actions.
""",
            "plan_generation": """
Given the market analysis:
{analysis}

Generate a {plan_type} trading plan with:
1. Entry conditions
2. Position sizing
3. Stop loss levels
4. Take profit targets
5. Risk management rules

Risk tolerance: {risk_tolerance}
""",
            "risk_assessment": """
Assess the risks for the following trading plan:
{plan}

Identify:
1. Maximum potential loss
2. Key risk factors
3. Mitigation strategies
4. Worst-case scenarios
"""
        }

    def create_plan(self,
                   market_state: NDArray[np.float64],
                   market_data: Dict[str, Any]) -> TradingPlan:
        """Create a trading plan based on market conditions."""
        # Analyze market conditions
        analysis = self._analyze_market(market_state, market_data)

        # Select plan type based on market conditions
        plan_type = self._select_plan_type(analysis)

        # Generate action sequence
        action_sequence = self._generate_actions(analysis, plan_type)

        # Generate reasoning
        reasoning = self._generate_reasoning(analysis, plan_type, action_sequence)

        # Risk assessment
        risk_assessment = self._assess_risks(action_sequence)

        # Expected outcome
        expected_outcome = self._predict_outcome(action_sequence)

        # Calculate confidence
        confidence = self._calculate_confidence(analysis, action_sequence)

        plan = TradingPlan(
            plan_type=plan_type,
            action_sequence=action_sequence,
            reasoning=reasoning,
            risk_assessment=risk_assessment,
            expected_outcome=expected_outcome,
            confidence=confidence,
            metadata={
                "market_conditions": analysis,
                "plan_type": plan_type.name
            }
        )

        self.planning_history.append(plan)
        logger.info(f"Created {plan_type.name} plan with {len(action_sequence)} actions")

        return plan

    def _analyze_market(self,
                       market_state: NDArray[np.float64],
                       market_data: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze current market conditions."""
        # Calculate basic metrics
        volatility = np.std(market_state) if len(market_state) > 1 else 0.0
        
        if len(market_state) >= 3:
            trend = np.mean(np.diff(market_state[-3:]))
        else:
            trend = 0.0

        # Determine trend direction
        if trend > 0.1:
            trend_direction = "uptrend"
        elif trend < -0.1:
            trend_direction = "downtrend"
        else:
            trend_direction = "sideways"

        # Determine volatility level
        if volatility > 1.0:
            vol_level = "high"
        elif volatility > 0.5:
            vol_level = "moderate"
        else:
            vol_level = "low"

        return {
            "trend": trend_direction,
            "trend_strength": float(abs(trend)),
            "volatility": vol_level,
            "volatility_value": float(volatility),
            "current_price": float(market_state[-1]) if len(market_state) > 0 else 0.0,
            "recent_high": float(np.max(market_state[-5:])) if len(market_state) >= 5 else 0.0,
            "recent_low": float(np.min(market_state[-5:])) if len(market_state) >= 5 else 0.0
        }

    def _select_plan_type(self, analysis: Dict[str, Any]) -> PlanType:
        """Select appropriate plan type based on analysis."""
        volatility = analysis["volatility"]
        trend_strength = analysis["trend_strength"]

        if volatility == "high":
            return PlanType.HEDGING
        elif trend_strength > 0.3:
            return PlanType.AGGRESSIVE
        elif volatility == "low" and trend_strength < 0.1:
            return PlanType.CONSERVATIVE
        else:
            return PlanType.BALANCED

    def _generate_actions(self,
                         analysis: Dict[str, Any],
                         plan_type: PlanType) -> List[Dict[str, Any]]:
        """Generate action sequence for the plan."""
        actions = []

        # Entry action
        if analysis["trend"] == "uptrend":
            actions.append({
                "type": "entry",
                "action": "buy",
                "condition": "price > moving_average",
                "size": self._position_size(plan_type, analysis)
            })
        elif analysis["trend"] == "downtrend":
            actions.append({
                "type": "entry",
                "action": "sell",
                "condition": "price < moving_average",
                "size": self._position_size(plan_type, analysis)
            })
        else:
            actions.append({
                "type": "entry",
                "action": "wait",
                "condition": "price breakout",
                "size": 0
            })

        # Risk management actions
        if plan_type != PlanType.HEDGING:
            actions.append({
                "type": "risk_management",
                "action": "set_stop_loss",
                "level": analysis["recent_low"] * 0.98,
                "reason": "protect against reversal"
            })

            actions.append({
                "type": "risk_management",
                "action": "set_take_profit",
                "level": analysis["recent_high"] * 1.02,
                "reason": "lock in gains"
            })

        # Exit conditions
        actions.append({
            "type": "exit",
            "action": "monitor_exit",
            "conditions": ["stop_loss_hit", "take_profit_hit", "trend_reversal"],
            "max_holding_period": "24h"
        })

        return actions[:self.config.max_actions]

    def _position_size(self, 
                      plan_type: PlanType,
                      analysis: Dict[str, Any]) -> float:
        """Calculate position size based on plan type and conditions."""
        base_size = {
            PlanType.CONSERVATIVE: 0.1,
            PlanType.BALANCED: 0.25,
            PlanType.AGGRESSIVE: 0.5,
            PlanType.HEDGING: 0.15
        }[plan_type]

        # Adjust for volatility
        if analysis["volatility"] == "high":
            base_size *= 0.7
        elif analysis["volatility"] == "low":
            base_size *= 1.2

        return min(base_size, 1.0)

    def _generate_reasoning(self,
                           analysis: Dict[str, Any],
                           plan_type: PlanType,
                           actions: List[Dict[str, Any]]) -> str:
        """Generate reasoning for the plan."""
        reasoning = f"Market Analysis: {analysis['trend']} with {analysis['volatility']} volatility. "
        reasoning += f"Selected {plan_type.name} approach based on conditions. "
        reasoning += f"Generated {len(actions)} actions with appropriate risk management."

        return reasoning

    def _assess_risks(self, actions: List[Dict[str, Any]]) -> str:
        """Assess risks of the plan."""
        risks = []

        for action in actions:
            if action["type"] == "entry" and action["action"] != "wait":
                risks.append(f"Position entry risk: {action['action']} at specified size")
            elif action["type"] == "risk_management":
                risks.append(f"Risk control: {action['action']}")

        return "; ".join(risks) if risks else "Standard market risks apply"

    def _predict_outcome(self, actions: List[Dict[str, Any]]) -> str:
        """Predict expected outcome."""
        entry_actions = [a for a in actions if a["type"] == "entry" and a["action"] != "wait"]
        
        if entry_actions:
            return "Expected positive return if trend continues as analyzed"
        else:
            return "No position entered - waiting for clearer signals"

    def _calculate_confidence(self,
                             analysis: Dict[str, Any],
                             actions: List[Dict[str, Any]]) -> float:
        """Calculate confidence in the plan."""
        # Higher confidence with stronger trends and lower volatility
        trend_strength = analysis["trend_strength"]
        volatility = analysis["volatility_value"]

        base_confidence = 0.5
        trend_boost = min(trend_strength * 0.3, 0.3)
        vol_penalty = min(volatility * 0.2, 0.2)

        confidence = base_confidence + trend_boost - vol_penalty
        
        # Adjust based on number of actions
        if len(actions) > 3:
            confidence += 0.1  # More comprehensive plan

        return max(0.3, min(0.9, confidence))


__all__ = [
    "LLMTradingPlanner",
    "PlannerConfig",
    "TradingPlan",
    "PlanType"
]