"""
Signal Quality Scorer — multi-factor quality gate for trading signals.

Every signal generated by ARGUS strategies passes through this scorer
before execution.  The scorer assigns a quality score (0–1) based on
multiple independent checks, and only signals that pass a minimum
threshold are forwarded for execution.

Quality factors checked:
1. **Confidence**: signal's own confidence exceeds minimum threshold
2. **Volume confirmation**: recent volume supports the signal direction
3. **Regime alignment**: signal direction matches the current market regime
4. **Trend alignment**: signal is not counter-trend (unless mean-reversion)
5. **Spread acceptability**: bid-ask spread is within acceptable bounds
6. **Time-of-day quality**: historical win rate for this hour is adequate
7. **Correlation penalty**: signal is not redundant with existing positions

The scorer also records outcomes (P&L per signal) and uses historical
performance to refine factor weights over time.  All data is persisted
to SQLite for learning across restarts.
"""

from __future__ import annotations

import logging
import os
import sqlite3
import threading
import time
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

_DEFAULT_DB_PATH = "data/signal_quality.db"


@dataclass
class SignalScore:
    """Result of scoring a signal."""

    quality: float  # 0.0 – 1.0
    reasons: List[str]  # human-readable pass/fail reasons
    passed: bool  # whether the signal passes the quality gate
    factors: Dict[str, float] = field(default_factory=dict)  # individual factor scores
    signal_id: Optional[str] = None

    def __repr__(self) -> str:
        status = "PASS" if self.passed else "FAIL"
        return f"SignalScore({status} quality={self.quality:.3f} factors={len(self.factors)})"


class SignalQualityScorer:
    """
    Multi-factor signal quality gate.

    Parameters
    ----------
    db_path : str
        SQLite database path for persistence and learning.
    min_quality : float
        Minimum quality score to pass (0.0–1.0).
    min_confidence : float
        Minimum signal confidence to pass.
    max_spread_bps : float
        Maximum acceptable bid-ask spread in basis points.
    volume_confirmation_ratio : float
        Minimum ratio of current volume to average for confirmation.
    time_quality_min_samples : int
        Minimum samples per hour before applying time-of-day factor.
    """

    def __init__(
        self,
        db_path: str = _DEFAULT_DB_PATH,
        min_quality: float = 0.5,
        min_confidence: float = 0.3,
        max_spread_bps: float = 50.0,
        volume_confirmation_ratio: float = 0.8,
        time_quality_min_samples: int = 20,
    ) -> None:
        self.db_path = db_path
        self.min_quality = max(0.0, min(1.0, min_quality))
        self.min_confidence = max(0.0, min(1.0, min_confidence))
        self.max_spread_bps = max(1.0, max_spread_bps)
        self.volume_confirmation_ratio = max(0.0, volume_confirmation_ratio)
        self.time_quality_min_samples = max(1, time_quality_min_samples)

        self._lock = threading.Lock()

        # Factor weights (updated by learning)
        self._weights: Dict[str, float] = {
            "confidence": 0.25,
            "volume": 0.15,
            "regime": 0.20,
            "trend": 0.15,
            "spread": 0.10,
            "time_of_day": 0.10,
            "correlation": 0.05,
        }

        # Outcome tracking: {factor_name: {pass_count, fail_count, total_pnl}}
        self._factor_outcomes: Dict[str, Dict[str, float]] = defaultdict(
            lambda: {"pass_count": 0, "fail_count": 0, "total_pnl": 0.0}
        )
        # Time-of-day win rates: {hour: {wins, losses}}
        self._hourly_outcomes: Dict[int, Dict[str, int]] = defaultdict(
            lambda: {"wins": 0, "losses": 0}
        )

        self._signal_counter = 0
        self._init_db()
        self._load_outcomes()

        logger.info(
            "SignalQualityScorer initialised (min_quality=%.2f, min_conf=%.2f, "
            "max_spread=%.1f bps, db=%s)",
            self.min_quality,
            self.min_confidence,
            self.max_spread_bps,
            self.db_path,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def score(self, signal: Dict[str, Any]) -> SignalScore:
        """
        Score a trading signal on multiple quality factors.

        Parameters
        ----------
        signal : dict
            Must contain at least ``"symbol"`` and ``"direction"``.
            Optional keys: ``"confidence"``, ``"volume"``, ``"avg_volume"``,
            ``"regime"``, ``"trend"``, ``"spread_bps"``, ``"hour"``,
            ``"correlation_to_portfolio"``.

        Returns
        -------
        SignalScore
            Quality assessment with pass/fail decision.
        """
        with self._lock:
            self._signal_counter += 1
            signal_id = f"sig_{int(time.time())}_{self._signal_counter}"

        reasons: List[str] = []
        factors: Dict[str, float] = {}

        # 1. Confidence check
        conf = float(signal.get("confidence", 0.0))
        if conf >= self.min_confidence:
            factors["confidence"] = min(conf / 1.0, 1.0)
            reasons.append(f"confidence={conf:.3f} >= {self.min_confidence:.3f}")
        else:
            factors["confidence"] = conf / max(self.min_confidence, 0.01)
            reasons.append(f"FAIL: confidence={conf:.3f} < {self.min_confidence:.3f}")

        # 2. Volume confirmation
        volume = float(signal.get("volume", 0.0))
        avg_volume = float(signal.get("avg_volume", 0.0))
        if avg_volume > 0 and volume > 0:
            vol_ratio = volume / avg_volume
            if vol_ratio >= self.volume_confirmation_ratio:
                factors["volume"] = min(vol_ratio / 2.0, 1.0)
                reasons.append(f"volume_ratio={vol_ratio:.2f} (confirmed)")
            else:
                factors["volume"] = vol_ratio / max(self.volume_confirmation_ratio, 0.01)
                reasons.append(f"FAIL: volume_ratio={vol_ratio:.2f} < {self.volume_confirmation_ratio:.2f}")
        else:
            factors["volume"] = 0.5  # neutral if no volume data
            reasons.append("volume: no data (neutral)")

        # 3. Regime alignment
        direction = str(signal.get("direction", "")).lower()
        regime = str(signal.get("regime", "")).lower()
        if regime:
            regime_aligned = self._check_regime_alignment(direction, regime)
            factors["regime"] = 1.0 if regime_aligned else 0.2
            if regime_aligned:
                reasons.append(f"regime={regime} aligned with {direction}")
            else:
                reasons.append(f"FAIL: regime={regime} conflicts with {direction}")
        else:
            factors["regime"] = 0.5
            reasons.append("regime: unknown (neutral)")

        # 4. Trend alignment
        trend = str(signal.get("trend", "")).lower()
        if trend:
            trend_aligned = self._check_trend_alignment(direction, trend)
            factors["trend"] = 1.0 if trend_aligned else 0.3
            if trend_aligned:
                reasons.append(f"trend={trend} aligned with {direction}")
            else:
                reasons.append(f"WARN: counter-trend ({direction} vs trend={trend})")
        else:
            factors["trend"] = 0.5
            reasons.append("trend: unknown (neutral)")

        # 5. Spread check
        spread_bps = float(signal.get("spread_bps", 0.0))
        if spread_bps > 0:
            if spread_bps <= self.max_spread_bps:
                factors["spread"] = 1.0 - (spread_bps / self.max_spread_bps) * 0.5
                reasons.append(f"spread={spread_bps:.1f} bps (acceptable)")
            else:
                factors["spread"] = max(0.0, 1.0 - spread_bps / self.max_spread_bps)
                reasons.append(f"FAIL: spread={spread_bps:.1f} bps > max {self.max_spread_bps:.1f}")
        else:
            factors["spread"] = 0.7  # slightly positive default
            reasons.append("spread: no data (default OK)")

        # 6. Time-of-day quality
        hour = signal.get("hour")
        if hour is not None:
            hour = int(hour) % 24
            tod_score = self._get_time_quality(hour)
            factors["time_of_day"] = tod_score
            reasons.append(f"time_of_day hour={hour} score={tod_score:.2f}")
        else:
            factors["time_of_day"] = 0.5
            reasons.append("time_of_day: no hour (neutral)")

        # 7. Correlation penalty
        corr = float(signal.get("correlation_to_portfolio", 0.0))
        if corr > 0:
            # High correlation = lower quality (redundant signal)
            factors["correlation"] = max(0.0, 1.0 - corr)
            if corr > 0.7:
                reasons.append(f"WARN: high correlation={corr:.2f} to portfolio")
            else:
                reasons.append(f"correlation={corr:.2f} (acceptable)")
        else:
            factors["correlation"] = 1.0
            reasons.append("correlation: none (independent)")

        # Weighted quality score
        quality = 0.0
        total_weight = 0.0
        for factor_name, weight in self._weights.items():
            if factor_name in factors:
                quality += weight * factors[factor_name]
                total_weight += weight

        if total_weight > 0:
            quality /= total_weight

        quality = round(max(0.0, min(1.0, quality)), 4)
        passed = quality >= self.min_quality

        score = SignalScore(
            quality=quality,
            reasons=reasons,
            passed=passed,
            factors=factors,
            signal_id=signal_id,
        )

        logger.info(
            "Signal %s scored %.3f (%s) for %s %s",
            signal_id,
            quality,
            "PASS" if passed else "FAIL",
            signal.get("symbol", "?"),
            direction,
        )
        return score

    def record_outcome(self, signal_id: str, pnl: float) -> None:
        """
        Record the P&L outcome of a previously scored signal.

        This data is used to refine factor weights over time.

        Parameters
        ----------
        signal_id : str
            The signal_id from the SignalScore.
        pnl : float
            Realised P&L from executing this signal.
        """
        with self._lock:
            won = pnl > 0
            hour = datetime.now(timezone.utc).hour

            if won:
                self._hourly_outcomes[hour]["wins"] += 1
            else:
                self._hourly_outcomes[hour]["losses"] += 1

            self._persist_outcome(signal_id, pnl)

            logger.debug(
                "Recorded outcome for %s: pnl=%.4f (%s)",
                signal_id, pnl, "WIN" if won else "LOSS",
            )

    def get_pass_rate(self, lookback_days: int = 7) -> float:
        """
        Return the fraction of signals that passed quality gate recently.

        Parameters
        ----------
        lookback_days : int
            Number of days to look back.

        Returns
        -------
        float
            Pass rate (0.0–1.0), or 0.0 if no data.
        """
        try:
            conn = sqlite3.connect(self.db_path)
            try:
                cursor = conn.execute(
                    """
                    SELECT
                        COUNT(*) as total,
                        SUM(CASE WHEN passed = 1 THEN 1 ELSE 0 END) as passed
                    FROM signal_scores
                    WHERE scored_at >= datetime('now', ?)
                    """,
                    (f"-{lookback_days} days",),
                )
                row = cursor.fetchone()
                if row and row[0] > 0:
                    return round(row[1] / row[0], 4)
            finally:
                conn.close()
        except Exception:
            logger.exception("Failed to compute pass rate")
        return 0.0

    def get_factor_weights(self) -> Dict[str, float]:
        """Return the current factor weights."""
        return dict(self._weights)

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _check_regime_alignment(self, direction: str, regime: str) -> bool:
        """Check if signal direction aligns with market regime."""
        bullish_regimes = {"bullish", "trending_up", "risk_on", "expansion"}
        bearish_regimes = {"bearish", "trending_down", "risk_off", "contraction"}
        if direction == "buy" and regime in bullish_regimes:
            return True
        if direction == "sell" and regime in bearish_regimes:
            return True
        if regime in {"neutral", "ranging", "sideways", "unknown"}:
            return True  # neutral regime doesn't conflict
        return False

    def _check_trend_alignment(self, direction: str, trend: str) -> bool:
        """Check if signal direction aligns with the prevailing trend."""
        if direction == "buy" and trend in {"up", "bullish", "uptrend"}:
            return True
        if direction == "sell" and trend in {"down", "bearish", "downtrend"}:
            return True
        if trend in {"neutral", "sideways", "flat"}:
            return True
        return False

    def _get_time_quality(self, hour: int) -> float:
        """Return time-of-day quality score based on historical win rates."""
        with self._lock:
            data = self._hourly_outcomes.get(hour)
            if data is None:
                return 0.5

            total = data["wins"] + data["losses"]
            if total < self.time_quality_min_samples:
                return 0.5  # insufficient data

            win_rate = data["wins"] / total
            # Scale: 50% win rate → 0.5, 70% → 0.8, 30% → 0.2
            return round(min(1.0, max(0.0, win_rate)), 4)

    def _init_db(self) -> None:
        """Create SQLite tables."""
        os.makedirs(os.path.dirname(self.db_path) or ".", exist_ok=True)
        conn = sqlite3.connect(self.db_path)
        try:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS signal_scores (
                    signal_id TEXT PRIMARY KEY,
                    quality REAL NOT NULL,
                    passed INTEGER NOT NULL,
                    symbol TEXT,
                    direction TEXT,
                    factors_json TEXT,
                    scored_at TEXT NOT NULL DEFAULT (datetime('now'))
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS signal_outcomes (
                    signal_id TEXT PRIMARY KEY,
                    pnl REAL NOT NULL,
                    recorded_at TEXT NOT NULL DEFAULT (datetime('now'))
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS hourly_outcomes (
                    hour INTEGER PRIMARY KEY,
                    wins INTEGER NOT NULL DEFAULT 0,
                    losses INTEGER NOT NULL DEFAULT 0
                )
                """
            )
            conn.commit()
        finally:
            conn.close()

    def _persist_outcome(self, signal_id: str, pnl: float) -> None:
        """Persist an outcome to the database."""
        try:
            conn = sqlite3.connect(self.db_path)
            try:
                conn.execute(
                    """
                    INSERT OR REPLACE INTO signal_outcomes (signal_id, pnl)
                    VALUES (?, ?)
                    """,
                    (signal_id, pnl),
                )
                conn.commit()
            finally:
                conn.close()
        except Exception:
            logger.exception("Failed to persist signal outcome for %s", signal_id)

    def _load_outcomes(self) -> None:
        """Load historical outcome data from the database."""
        if not os.path.exists(self.db_path):
            return
        try:
            conn = sqlite3.connect(self.db_path)
            try:
                cursor = conn.execute("SELECT hour, wins, losses FROM hourly_outcomes")
                for hour, wins, losses in cursor:
                    self._hourly_outcomes[hour] = {"wins": wins, "losses": losses}
            finally:
                conn.close()
        except Exception:
            logger.exception("Failed to load outcome data from %s", self.db_path)
