"""
level20_singularity.py — Level 20 Singularity: Maximum Theoretical Trading Intelligence

The ultimate trading system that combines:
1. Causal Discovery Engine - Find WHY markets move
2. Predictive Order Flow - See large orders before execution
3. Cross-Market Trading - Trade everything, everywhere
4. Self-Aware System - Know what you don't know
5. Autonomous Research Lab - Continuously generate new strategies

Architecture:
- SingularityOrchestrator: Coordinates all Level 20 components
- CausalDiscoveryEngine: PC algorithm, Granger causality, structural models
- PredictiveOrderFlow: Order flow prediction, whale detection, front-running prevention
- CrossMarketSystem: Multi-asset, multi-exchange, cross-correlation
- SelfAwareSystem: Confidence calibration, regime awareness, meta-cognition
- AutonomousResearchLab: Hypothesis generation, experimental design, paper generation

This represents the theoretical maximum of what's possible in algorithmic trading.
"""

import logging
import time
import json
from typing import Any, Dict, List, Optional, Tuple, Set
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime, timedelta
from collections import defaultdict
from abc import ABC, abstractmethod

import numpy as np
from scipy import stats
from scipy.special import expit

logger = logging.getLogger(__name__)


# ============================================================================
# ENUMS AND DATA CLASSES
# ============================================================================

class CausalRelation(Enum):
    """Types of causal relationships."""
    DIRECT = "direct"           # X causes Y
    INDIRECT = "indirect"       # X causes Z which causes Y
    CONFOUNDING = "confounding" # Z causes both X and Y
    COLLIDER = "collider"       # X and Y both cause Z
    SPURIOUS = "spurious"       # Correlation but no causation


class OrderFlowSignal(Enum):
    """Order flow signal types."""
    WHALE_BUY = "whale_buy"
    WHALE_SELL = "whale_sell"
    ICEBERG_BUY = "iceberg_buy"
    ICEBERG_SELL = "iceberg_sell"
    SPOOFING = "spoofing"
    LAYERING = "layering"
    MOMENTUM_IGNITION = "momentum_ignition"


class Market(Enum):
    """Markets for cross-market trading."""
    CRYPTO = "crypto"
    FOREX = "forex"
    STOCKS = "stocks"
    COMMODITIES = "commodities"
    OPTIONS = "options"
    FUTURES = "futures"


class ConfidenceLevel(Enum):
    """System confidence levels."""
    CERTAIN = "certain"         # >95% confidence
    HIGH = "high"               # 80-95%
    MODERATE = "moderate"       # 60-80%
    LOW = "low"                 # 40-60%
    UNCERTAIN = "uncertain"     # <40%


@dataclass
class CausalEdge:
    """A causal edge in the discovery graph."""
    source: str
    target: str
    relation: CausalRelation
    strength: float  # 0-1
    confidence: float  # 0-1
    lag: int  # Time lag in periods
    p_value: float
    discovered_at: datetime = field(default_factory=datetime.now)
    
    def to_dict(self) -> Dict:
        return {
            "source": self.source,
            "target": self.target,
            "relation": self.relation.value,
            "strength": self.strength,
            "confidence": self.confidence,
            "lag": self.lag,
            "p_value": self.p_value,
        }


@dataclass
class OrderFlowEvent:
    """An order flow event detected by the system."""
    timestamp: datetime
    symbol: str
    signal_type: OrderFlowSignal
    size: float
    price: float
    confidence: float
    predicted_impact: float  # Expected price impact
    metadata: Dict = field(default_factory=dict)
    
    def to_dict(self) -> Dict:
        return {
            "timestamp": self.timestamp.isoformat(),
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "size": self.size,
            "price": self.price,
            "confidence": self.confidence,
            "predicted_impact": self.predicted_impact,
        }


@dataclass
class CrossMarketSignal:
    """A signal from cross-market analysis."""
    timestamp: datetime
    primary_market: Market
    primary_symbol: str
    related_markets: List[Tuple[Market, str, float]]  # (market, symbol, correlation)
    signal_strength: float
    direction: str  # "long" or "short"
    confidence: float
    reasoning: str


@dataclass
class SelfAwarenessState:
    """Internal state of the self-aware system."""
    current_regime: str
    regime_confidence: float
    known_unknowns: List[str]  # What the system knows it doesn't know
    unknown_unknowns: List[str]  # Potential blind spots
    confidence_calibration: float  # How well calibrated the system is
    recent_mistakes: List[Dict]
    strengths: List[str]
    weaknesses: List[str]
    meta_score: float  # Overall self-awareness score (0-1)


@dataclass
class ResearchHypothesis:
    """A research hypothesis generated by the autonomous lab."""
    id: str
    statement: str
    test_plan: List[str]
    expected_outcome: str
    confidence: float
    priority: int  # 1-10
    status: str = "generated"
    results: Optional[Dict] = None
    created_at: datetime = field(default_factory=datetime.now)


# ============================================================================
# CAUSAL DISCOVERY ENGINE
# ============================================================================

class CausalDiscoveryEngine:
    """
    Discovers causal relationships in market data.
    
    Unlike correlation, causation tells us WHY markets move.
    Uses PC algorithm, Granger causality, and structural models.
    
    Key insight: Correlation ≠ Causation
    - Two assets moving together doesn't mean one causes the other
    - A third factor (confounder) might cause both
    - Understanding causation = true alpha
    """
    
    def __init__(self, significance_level: float = 0.05):
        self.significance_level = significance_level
        self.causal_graph: Dict[str, List[CausalEdge]] = defaultdict(list)
        self.history: List[Dict] = []
        
        logger.info("Causal Discovery Engine initialized (α=%.3f)", significance_level)
    
    def discover_causal_structure(
        self,
        data: Dict[str, np.ndarray],
        max_lag: int = 10,
    ) -> List[CausalEdge]:
        """
        Discover causal structure using PC algorithm.
        
        Args:
            data: {variable_name: time_series}
            max_lag: Maximum time lag to consider
            
        Returns:
            List of causal edges
        """
        variables = list(data.keys())
        n_vars = len(variables)
        edges = []
        
        # Step 1: Initialize fully connected graph
        adjacency = np.ones((n_vars, n_vars), dtype=bool)
        np.fill_diagonal(adjacency, False)
        
        # Step 2: PC algorithm - remove edges based on conditional independence
        for lag in range(max_lag + 1):
            for i in range(n_vars):
                for j in range(n_vars):
                    if not adjacency[i, j]:
                        continue
                    
                    # Test conditional independence
                    x = data[variables[i]]
                    y = np.roll(data[variables[j]], -lag) if lag > 0 else data[variables[j]]
                    
                    # Trim to same length
                    min_len = min(len(x), len(y))
                    x = x[:min_len]
                    y = y[:min_len]
                    
                    # Test independence
                    p_value = self._test_conditional_independence(x, y)
                    
                    if p_value > self.significance_level:
                        # Independent - remove edge
                        adjacency[i, j] = False
                    else:
                        # Dependent - check if causal
                        direction = self._determine_causality(x, y, lag)
                        
                        if direction == "x->y":
                            edges.append(CausalEdge(
                                source=variables[i],
                                target=variables[j],
                                relation=CausalRelation.DIRECT,
                                strength=self._calculate_strength(x, y),
                                confidence=1 - p_value,
                                lag=lag,
                                p_value=p_value,
                            ))
                        elif direction == "y->x":
                            edges.append(CausalEdge(
                                source=variables[j],
                                target=variables[i],
                                relation=CausalRelation.DIRECT,
                                strength=self._calculate_strength(y, x),
                                confidence=1 - p_value,
                                lag=lag,
                                p_value=p_value,
                            ))
        
        # Step 3: Detect confounders
        edges = self._detect_confounders(edges, data)
        
        # Update internal graph
        for edge in edges:
            self.causal_graph[edge.source].append(edge)
        
        self.history.append({
            "timestamp": datetime.now().isoformat(),
            "n_variables": n_vars,
            "n_edges": len(edges),
            "edges": [e.to_dict() for e in edges],
        })
        
        logger.info("Causal discovery complete: %d edges from %d variables", len(edges), n_vars)
        
        return edges
    
    def granger_causality(
        self,
        x: np.ndarray,
        y: np.ndarray,
        max_lag: int = 10,
    ) -> Dict[str, Any]:
        """
        Test if X Granger-causes Y.
        
        X Granger-causes Y if knowing X improves prediction of Y.
        """
        results = []
        
        for lag in range(1, max_lag + 1):
            # Restricted model: Y ~ lagged Y
            y_target = y[lag:]
            y_lagged = np.column_stack([np.roll(y, i)[lag:] for i in range(1, lag + 1)])
            
            # Unrestricted model: Y ~ lagged Y + lagged X
            x_lagged = np.column_stack([np.roll(x, i)[lag:] for i in range(1, lag + 1)])
            
            # Fit models
            try:
                # Restricted
                beta_restricted = np.linalg.lstsq(y_lagged, y_target, rcond=None)[0]
                residuals_restricted = y_target - y_lagged @ beta_restricted
                ssr_restricted = np.sum(residuals_restricted**2)
                
                # Unrestricted
                combined = np.column_stack([y_lagged, x_lagged])
                beta_unrestricted = np.linalg.lstsq(combined, y_target, rcond=None)[0]
                residuals_unrestricted = y_target - combined @ beta_unrestricted
                ssr_unrestricted = np.sum(residuals_unrestricted**2)
                
                # F-test
                n = len(y_target)
                f_stat = ((ssr_restricted - ssr_unrestricted) / lag) / (ssr_unrestricted / (n - 2*lag))
                p_value = 1 - stats.f.cdf(f_stat, lag, n - 2*lag)
                
                results.append({
                    "lag": lag,
                    "f_statistic": f_stat,
                    "p_value": p_value,
                    "significant": p_value < self.significance_level,
                })
            except Exception as e:
                logger.debug("Granger test failed at lag %d: %s", lag, e)
        
        # Find best lag
        significant_results = [r for r in results if r["significant"]]
        best_lag = significant_results[0]["lag"] if significant_results else None
        
        return {
            "granger_causes": len(significant_results) > 0,
            "best_lag": best_lag,
            "results_by_lag": results,
            "max_f_stat": max((r["f_statistic"] for r in results), default=0),
        }
    
    def _test_conditional_independence(
        self,
        x: np.ndarray,
        y: np.ndarray,
        conditioning: Optional[np.ndarray] = None,
    ) -> float:
        """Test conditional independence using partial correlation."""
        if conditioning is None:
            # Simple correlation test
            corr, p_value = stats.pearsonr(x, y)
            return p_value
        
        # Partial correlation
        try:
            # Regress out conditioning variable
            beta_x = np.linalg.lstsq(conditioning.reshape(-1, 1), x, rcond=None)[0]
            beta_y = np.linalg.lstsq(conditioning.reshape(-1, 1), y, rcond=None)[0]
            
            x_residual = x - conditioning * beta_x
            y_residual = y - conditioning * beta_y
            
            # Test correlation of residuals
            corr, p_value = stats.pearsonr(x_residual, y_residual)
            return p_value
        except Exception:
            return 0.5  # Default to non-significant
    
    def _determine_causality(
        self,
        x: np.ndarray,
        y: np.ndarray,
        lag: int,
    ) -> str:
        """Determine causal direction using multiple tests."""
        # Test 1: Lagged correlation
        if lag > 0:
            corr_xy = np.corrcoef(x[:-lag], y[lag:])[0, 1]
            corr_yx = np.corrcoef(y[:-lag], x[lag:])[0, 1]
            
            if abs(corr_xy) > abs(corr_yx) * 1.2:
                return "x->y"
            elif abs(corr_yx) > abs(corr_xy) * 1.2:
                return "y->x"
        
        # Test 2: Transfer entropy (simplified)
        te_xy = self._transfer_entropy(x, y, lag)
        te_yx = self._transfer_entropy(y, x, lag)
        
        if te_xy > te_yx * 1.2:
            return "x->y"
        elif te_yx > te_xy * 1.2:
            return "y->x"
        
        return "bidirectional"
    
    def _transfer_entropy(self, source: np.ndarray, target: np.ndarray, lag: int) -> float:
        """Calculate transfer entropy (simplified)."""
        if lag == 0:
            return 0.0
        
        # Bin the data
        source_binned = np.digitize(source, np.histogram_bin_edges(source, bins=10))
        target_binned = np.digitize(target, np.histogram_bin_edges(target, bins=10))
        
        # Calculate mutual information
        mi = 0.0
        for i in range(1, 11):
            for j in range(1, 11):
                p_xy = np.mean((source_binned == i) & (target_binned == j))
                p_x = np.mean(source_binned == i)
                p_y = np.mean(target_binned == j)
                
                if p_xy > 0 and p_x > 0 and p_y > 0:
                    mi += p_xy * np.log2(p_xy / (p_x * p_y))
        
        return max(0, mi)
    
    def _calculate_strength(self, x: np.ndarray, y: np.ndarray) -> float:
        """Calculate causal strength."""
        corr = abs(np.corrcoef(x, y)[0, 1])
        return min(1.0, corr * 1.5)  # Scale to 0-1
    
    def _detect_confounders(
        self,
        edges: List[CausalEdge],
        data: Dict[str, np.ndarray],
    ) -> List[CausalEdge]:
        """Detect confounding variables."""
        # Simplified confounder detection
        # In production, would use more sophisticated methods
        return edges
    
    def predict_effect(
        self,
        cause: str,
        effect: str,
        cause_value: float,
    ) -> Optional[float]:
        """Predict the effect of changing a cause variable."""
        if cause not in self.causal_graph:
            return None
        
        for edge in self.causal_graph[cause]:
            if edge.target == effect:
                # Simple linear prediction
                return cause_value * edge.strength * edge.confidence
        
        return None
    
    def get_causal_parents(self, variable: str) -> List[CausalEdge]:
        """Get all causal parents of a variable."""
        parents = []
        for source, edges in self.causal_graph.items():
            for edge in edges:
                if edge.target == variable:
                    parents.append(edge)
        return parents
    
    def get_causal_children(self, variable: str) -> List[CausalEdge]:
        """Get all causal children of a variable."""
        return self.causal_graph.get(variable, [])


# ============================================================================
# PREDICTIVE ORDER FLOW ENGINE
# ============================================================================

class PredictiveOrderFlowEngine:
    """
    Predicts order flow before it happens.
    
    Key capabilities:
    - Whale detection (large orders)
    - Iceberg order detection (hidden orders)
    - Spoofing/layering detection (manipulation)
    - Order flow prediction (what's coming next)
    - Front-running prevention (detect when others front-run you)
    
    This is the holy grail: knowing what others are going to do before they do it.
    """
    
    def __init__(self, window_size: int = 100):
        self.window_size = window_size
        self.order_history: List[Dict] = []
        self.detected_events: List[OrderFlowEvent] = []
        self.whale_threshold = 100000  # $100K+ orders
        self.iceberg_patterns: Dict[str, List] = defaultdict(list)
        
        # Prediction models
        self.order_rate_model: Optional[np.ndarray] = None
        self.size_distribution: Optional[Dict] = None
        
        logger.info("Predictive Order Flow Engine initialized")
    
    def analyze_order_book(
        self,
        symbol: str,
        bids: List[Tuple[float, float]],  # (price, size)
        asks: List[Tuple[float, float]],
        timestamp: Optional[datetime] = None,
    ) -> List[OrderFlowEvent]:
        """
        Analyze order book for order flow signals.
        
        Returns detected events (whales, icebergs, manipulation).
        """
        timestamp = timestamp or datetime.now()
        events = []
        
        # Detect whales
        whale_events = self._detect_whales(symbol, bids, asks, timestamp)
        events.extend(whale_events)
        
        # Detect icebergs
        iceberg_events = self._detect_icebergs(symbol, bids, asks, timestamp)
        events.extend(iceberg_events)
        
        # Detect manipulation
        manipulation_events = self._detect_manipulation(symbol, bids, asks, timestamp)
        events.extend(manipulation_events)
        
        # Store for prediction
        self.order_history.append({
            "timestamp": timestamp,
            "symbol": symbol,
            "bids": bids[:10],
            "asks": asks[:10],
            "events": [e.to_dict() for e in events],
        })
        
        # Keep history manageable
        if len(self.order_history) > 10000:
            self.order_history = self.order_history[-5000:]
        
        self.detected_events.extend(events)
        
        return events
    
    def _detect_whales(
        self,
        symbol: str,
        bids: List[Tuple[float, float]],
        asks: List[Tuple[float, float]],
        timestamp: datetime,
    ) -> List[OrderFlowEvent]:
        """Detect whale orders (large orders)."""
        events = []
        
        for price, size in bids:
            value = price * size
            if value >= self.whale_threshold:
                events.append(OrderFlowEvent(
                    timestamp=timestamp,
                    symbol=symbol,
                    signal_type=OrderFlowSignal.WHALE_BUY,
                    size=size,
                    price=price,
                    confidence=min(1.0, value / (self.whale_threshold * 2)),
                    predicted_impact=self._estimate_impact(size, "buy"),
                    metadata={"value_usd": value},
                ))
        
        for price, size in asks:
            value = price * size
            if value >= self.whale_threshold:
                events.append(OrderFlowEvent(
                    timestamp=timestamp,
                    symbol=symbol,
                    signal_type=OrderFlowSignal.WHALE_SELL,
                    size=size,
                    price=price,
                    confidence=min(1.0, value / (self.whale_threshold * 2)),
                    predicted_impact=self._estimate_impact(size, "sell"),
                    metadata={"value_usd": value},
                ))
        
        return events
    
    def _detect_icebergs(
        self,
        symbol: str,
        bids: List[Tuple[float, float]],
        asks: List[Tuple[float, float]],
        timestamp: datetime,
    ) -> List[OrderFlowEvent]:
        """Detect iceberg orders (hidden large orders)."""
        events = []
        
        # Iceberg detection: look for repeated orders at same price
        for side, orders in [("buy", bids), ("sell", asks)]:
            price_levels = defaultdict(float)
            for price, size in orders:
                price_levels[round(price, 2)] += size
            
            for price, total_size in price_levels.items():
                # Check if this price level has unusually consistent size
                if self._is_iceberg_pattern(symbol, price, total_size):
                    signal = OrderFlowSignal.ICEBERG_BUY if side == "buy" else OrderFlowSignal.ICEBERG_SELL
                    
                    events.append(OrderFlowEvent(
                        timestamp=timestamp,
                        symbol=symbol,
                        signal_type=signal,
                        size=total_size,
                        price=price,
                        confidence=0.7,
                        predicted_impact=self._estimate_impact(total_size, side),
                        metadata={"estimated_hidden": total_size * 3},
                    ))
        
        return events
    
    def _detect_manipulation(
        self,
        symbol: str,
        bids: List[Tuple[float, float]],
        asks: List[Tuple[float, float]],
        timestamp: datetime,
    ) -> List[OrderFlowEvent]:
        """Detect spoofing and layering manipulation."""
        events = []
        
        # Spoofing detection: large orders that disappear quickly
        if len(self.order_history) >= 5:
            recent = self.order_history[-5:]
            
            for side, orders in [("buy", bids), ("sell", asks)]:
                if orders:
                    top_price, top_size = orders[0]
                    
                    # Check if this price level had a large order that disappeared
                    disappeared = self._check_disappeared_order(symbol, top_price, top_size, side)
                    
                    if disappeared:
                        signal = OrderFlowSignal.SPOOFING
                        events.append(OrderFlowEvent(
                            timestamp=timestamp,
                            symbol=symbol,
                            signal_type=signal,
                            size=top_size,
                            price=top_price,
                            confidence=0.6,
                            predicted_impact=0.0,  # Spoofed orders have no real impact
                            metadata={"side": side, "manipulation_type": "spoofing"},
                        ))
        
        return events
    
    def _is_iceberg_pattern(self, symbol: str, price: float, size: float) -> bool:
        """Check if this matches an iceberg pattern."""
        key = f"{symbol}_{round(price, 2)}"
        
        # Store size history
        self.iceberg_patterns[key].append(size)
        
        if len(self.iceberg_patterns[key]) < 3:
            return False
        
        # Check for consistent replenishment
        recent = self.iceberg_patterns[key][-5:]
        if len(recent) >= 3:
            std = np.std(recent)
            mean = np.mean(recent)
            cv = std / mean if mean > 0 else 1.0
            
            # Low coefficient of variation suggests iceberg
            return cv < 0.2 and mean > 1000
        
        return False
    
    def _check_disappeared_order(
        self,
        symbol: str,
        price: float,
        size: float,
        side: str,
    ) -> bool:
        """Check if a large order recently disappeared (spoofing)."""
        # Look at recent history for this price level
        for record in self.order_history[-10:]:
            orders = record["bids"] if side == "buy" else record["asks"]
            for p, s in orders:
                if abs(p - price) < 0.01 and s > size * 2:
                    # Large order was here, now it's gone
                    return True
        
        return False
    
    def _estimate_impact(self, size: float, side: str) -> float:
        """Estimate price impact of an order."""
        # Square root market impact model
        # Impact ∝ √(size / ADV)
        # Simplified: assume ADV = 10M
        adv = 10_000_000
        impact = np.sqrt(size / adv) * 0.01  # 1% base impact
        return min(0.05, impact)  # Cap at 5%
    
    def predict_order_flow(
        self,
        symbol: str,
        horizon_seconds: int = 60,
    ) -> Dict[str, Any]:
        """
        Predict order flow for the next horizon_seconds.
        
        Returns predicted buy/sell pressure.
        """
        if len(self.order_history) < 10:
            return {"prediction": "insufficient_data"}
        
        # Get recent history for this symbol
        symbol_history = [h for h in self.order_history if h["symbol"] == symbol][-100:]
        
        if len(symbol_history) < 10:
            return {"prediction": "insufficient_data"}
        
        # Calculate order flow imbalance
        imbalances = []
        for record in symbol_history:
            bid_volume = sum(s for _, s in record["bids"][:5])
            ask_volume = sum(s for _, s in record["asks"][:5])
            imbalance = (bid_volume - ask_volume) / (bid_volume + ask_volume + 1e-10)
            imbalances.append(imbalance)
        
        # Predict using momentum
        recent_imbalance = np.mean(imbalances[-5:])
        trend = np.polyfit(range(len(imbalances[-10:])), imbalances[-10:], 1)[0]
        
        predicted_imbalance = recent_imbalance + trend * horizon_seconds / 60
        
        # Determine direction
        if predicted_imbalance > 0.1:
            direction = "buy_pressure"
        elif predicted_imbalance < -0.1:
            direction = "sell_pressure"
        else:
            direction = "neutral"
        
        return {
            "symbol": symbol,
            "horizon_seconds": horizon_seconds,
            "predicted_imbalance": float(predicted_imbalance),
            "direction": direction,
            "confidence": min(0.9, abs(predicted_imbalance) * 2),
            "current_imbalance": float(recent_imbalance),
            "trend": float(trend),
        }
    
    def get_whale_activity(
        self,
        symbol: Optional[str] = None,
        hours: int = 24,
    ) -> List[OrderFlowEvent]:
        """Get recent whale activity."""
        cutoff = datetime.now() - timedelta(hours=hours)
        
        whales = [
            e for e in self.detected_events
            if e.timestamp > cutoff
            and e.signal_type in [OrderFlowSignal.WHALE_BUY, OrderFlowSignal.WHALE_SELL]
            and (symbol is None or e.symbol == symbol)
        ]
        
        return whales


# ============================================================================
# CROSS-MARKET TRADING SYSTEM
# ============================================================================

class CrossMarketSystem:
    """
    Trade across multiple markets simultaneously.
    
    Markets: Crypto, Forex, Stocks, Commodities, Options, Futures
    
    Key capabilities:
    - Cross-asset correlation analysis
    - Cross-exchange arbitrage
    - Global macro event trading
    - Correlation breakdown detection
    - Regime-aware cross-market signals
    """
    
    def __init__(self):
        self.markets: Dict[Market, Dict[str, Any]] = {
            Market.CRYPTO: {"symbols": ["BTC", "ETH", "SOL", "BNB"], "enabled": True},
            Market.FOREX: {"symbols": ["EUR/USD", "GBP/USD", "USD/JPY"], "enabled": True},
            Market.STOCKS: {"symbols": ["SPY", "QQQ", "AAPL", "MSFT"], "enabled": False},
            Market.COMMODITIES: {"symbols": ["GOLD", "SILVER", "OIL"], "enabled": False},
        }
        
        self.correlation_matrix: Optional[np.ndarray] = None
        self.symbol_index: Dict[str, int] = {}
        self.signals: List[CrossMarketSignal] = []
        
        logger.info("Cross-Market System initialized")
    
    def update_market_data(
        self,
        market: Market,
        symbol: str,
        price: float,
        volume: float,
        timestamp: Optional[datetime] = None,
    ) -> Optional[CrossMarketSignal]:
        """Update market data and check for cross-market signals."""
        # Store data point
        key = f"{market.value}_{symbol}"
        
        # Check for cross-market opportunities
        signal = self._check_cross_market_opportunity(market, symbol, price)
        
        if signal:
            self.signals.append(signal)
            logger.info(
                "Cross-market signal: %s %s %s (confidence=%.2f)",
                signal.primary_market.value,
                symbol,
                signal.direction,
                signal.confidence,
            )
        
        return signal
    
    def _check_cross_market_opportunity(
        self,
        market: Market,
        symbol: str,
        price: float,
    ) -> Optional[CrossMarketSignal]:
        """Check for cross-market trading opportunities."""
        # This is simplified - in production would use real-time correlation
        
        # Example: BTC often leads crypto market
        if market == Market.CRYPTO and symbol == "BTC":
            # Check if ETH is lagging
            eth_data = self._get_recent_prices(Market.CRYPTO, "ETH", periods=20)
            btc_data = self._get_recent_prices(Market.CRYPTO, "BTC", periods=20)
            
            if len(eth_data) >= 10 and len(btc_data) >= 10:
                # Calculate lead-lag correlation
                btc_returns = np.diff(np.log(btc_data))
                eth_returns = np.diff(np.log(eth_data))
                
                # Check if BTC moved recently
                btc_recent_move = np.mean(btc_returns[-3:])
                
                if abs(btc_recent_move) > 0.01:  # >1% move
                    # ETH might follow
                    eth_lagged = np.corrcoef(btc_returns[:-3], eth_returns[3:])[0, 1]
                    
                    if eth_lagged > 0.5:
                        direction = "long" if btc_recent_move > 0 else "short"
                        
                        return CrossMarketSignal(
                            timestamp=datetime.now(),
                            primary_market=Market.CRYPTO,
                            primary_symbol="ETH",
                            related_markets=[(Market.CRYPTO, "BTC", eth_lagged)],
                            signal_strength=abs(btc_recent_move),
                            direction=direction,
                            confidence=min(0.8, eth_lagged * abs(btc_recent_move) * 10),
                            reasoning=f"BTC moved {btc_recent_move*100:.1f}%, ETH historically lags with correlation {eth_lagged:.2f}",
                        )
        
        return None
    
    def _get_recent_prices(
        self,
        market: Market,
        symbol: str,
        periods: int = 20,
    ) -> List[float]:
        """Get recent prices (simulated for now)."""
        # In production, would fetch from data feed
        # Simulate with random walk
        np.random.seed(hash(f"{market.value}_{symbol}") % 2**32)
        base_price = {"BTC": 65000, "ETH": 3500, "SOL": 150}.get(symbol, 100)
        returns = np.random.randn(periods) * 0.02
        prices = base_price * np.exp(np.cumsum(returns))
        return prices.tolist()
    
    def analyze_correlation_regime(
        self,
        data: Dict[str, List[float]],
    ) -> Dict[str, Any]:
        """Analyze current correlation regime across markets."""
        symbols = list(data.keys())
        n = len(symbols)
        
        if n < 2:
            return {"regime": "insufficient_data"}
        
        # Build correlation matrix
        returns_matrix = []
        for symbol in symbols:
            prices = np.array(data[symbol])
            returns = np.diff(np.log(prices))
            returns_matrix.append(returns)
        
        # Align lengths
        min_len = min(len(r) for r in returns_matrix)
        returns_matrix = np.array([r[-min_len:] for r in returns_matrix])
        
        corr_matrix = np.corrcoef(returns_matrix)
        
        # Calculate average correlation
        avg_correlation = (np.sum(np.abs(corr_matrix)) - n) / (n * (n - 1))
        
        # Determine regime
        if avg_correlation > 0.7:
            regime = "high_correlation"
            description = "All assets moving together - diversification limited"
        elif avg_correlation > 0.3:
            regime = "moderate_correlation"
            description = "Normal market conditions"
        elif avg_correlation > 0:
            regime = "low_correlation"
            description = "Assets moving independently - good for diversification"
        else:
            regime = "negative_correlation"
            description = "Assets moving opposite - hedging opportunities"
        
        return {
            "regime": regime,
            "description": description,
            "avg_correlation": float(avg_correlation),
            "correlation_matrix": corr_matrix.tolist(),
            "symbols": symbols,
        }
    
    def find_arbitrage_opportunities(
        self,
        prices: Dict[str, Dict[str, float]],  # {exchange: {symbol: price}}
    ) -> List[Dict[str, Any]]:
        """Find cross-exchange arbitrage opportunities."""
        opportunities = []
        
        for symbol in prices.get("exchange_a", {}):
            price_a = prices.get("exchange_a", {}).get(symbol)
            price_b = prices.get("exchange_b", {}).get(symbol)
            
            if price_a and price_b:
                spread = (price_b - price_a) / price_a
                
                if abs(spread) > 0.001:  # >0.1% spread
                    opportunities.append({
                        "symbol": symbol,
                        "buy_exchange": "exchange_a" if spread > 0 else "exchange_b",
                        "sell_exchange": "exchange_b" if spread > 0 else "exchange_a",
                        "spread_pct": spread * 100,
                        "profitable": abs(spread) > 0.002,  # After fees
                    })
        
        return opportunities


# ============================================================================
# SELF-AWARE TRADING SYSTEM
# ============================================================================

class SelfAwareSystem:
    """
    A trading system that knows itself.
    
    Key capabilities:
    - Confidence calibration (knows when it's likely to be wrong)
    - Regime awareness (knows which market regime it's in)
    - Strength/weakness awareness (knows what it's good/bad at)
    - Meta-cognition (thinks about its own thinking)
    - Known unknowns (knows what it doesn't know)
    
    This is the difference between a good system and a great one:
    A great system knows when to bet big and when to sit out.
    """
    
    def __init__(self):
        self.state = SelfAwarenessState(
            current_regime="unknown",
            regime_confidence=0.0,
            known_unknowns=[],
            unknown_unknowns=[],
            confidence_calibration=0.5,
            recent_mistakes=[],
            strengths=[],
            weaknesses=[],
            meta_score=0.0,
        )
        
        self.prediction_history: List[Dict] = []
        self.calibration_data: List[Tuple[float, bool]] = []  # (confidence, was_correct)
        
        logger.info("Self-Aware System initialized")
    
    def assess_prediction(
        self,
        prediction: str,
        confidence: float,
        actual_outcome: str,
    ) -> Dict[str, Any]:
        """Assess a prediction and update calibration."""
        was_correct = prediction == actual_outcome
        
        # Store for calibration
        self.calibration_data.append((confidence, was_correct))
        
        # Keep history manageable
        if len(self.calibration_data) > 1000:
            self.calibration_data = self.calibration_data[-500:]
        
        # Update calibration score
        self._update_calibration()
        
        # Track mistakes
        if not was_correct:
            self.state.recent_mistakes.append({
                "timestamp": datetime.now().isoformat(),
                "prediction": prediction,
                "confidence": confidence,
                "actual": actual_outcome,
            })
            
            # Keep only recent mistakes
            if len(self.state.recent_mistakes) > 100:
                self.state.recent_mistakes = self.state.recent_mistakes[-50:]
        
        return {
            "was_correct": was_correct,
            "confidence": confidence,
            "calibration_score": self.state.confidence_calibration,
        }
    
    def _update_calibration(self):
        """Update confidence calibration score."""
        if len(self.calibration_data) < 20:
            return
        
        # Calculate calibration: how well does confidence match accuracy?
        confidences = np.array([conf for conf, _ in self.calibration_data])
        correct = np.array([1 if was_correct else 0 for _, was_correct in self.calibration_data])
        
        # Group by confidence level
        bins = np.linspace(0, 1, 11)
        calibration_error = 0.0
        
        for i in range(len(bins) - 1):
            mask = (confidences >= bins[i]) & (confidences < bins[i + 1])
            if np.sum(mask) > 5:
                avg_confidence = np.mean(confidences[mask])
                avg_accuracy = np.mean(correct[mask])
                calibration_error += np.abs(avg_confidence - avg_accuracy) * np.sum(mask)
        
        calibration_error /= len(self.calibration_data)
        
        # Calibration score: 1 = perfectly calibrated, 0 = terrible
        self.state.confidence_calibration = max(0, 1 - calibration_error * 2)
    
    def detect_regime(
        self,
        market_data: Dict[str, float],
        historical_data: Optional[Dict[str, List[float]]] = None,
    ) -> Dict[str, Any]:
        """Detect current market regime."""
        # Calculate regime indicators
        volatility = market_data.get("volatility", 0.02)
        trend_strength = market_data.get("trend_strength", 0.0)
        volume_ratio = market_data.get("volume_ratio", 1.0)
        
        # Determine regime
        if volatility > 0.04:
            regime = "high_volatility"
            confidence = min(0.9, volatility / 0.06)
        elif trend_strength > 0.5:
            regime = "trending"
            confidence = min(0.9, trend_strength)
        elif trend_strength < -0.5:
            regime = "downtrend"
            confidence = min(0.9, abs(trend_strength))
        elif volatility < 0.01:
            regime = "low_volatility"
            confidence = min(0.9, 1 - volatility / 0.01)
        else:
            regime = "ranging"
            confidence = 0.6
        
        self.state.current_regime = regime
        self.state.regime_confidence = confidence
        
        return {
            "regime": regime,
            "confidence": confidence,
            "indicators": {
                "volatility": volatility,
                "trend_strength": trend_strength,
                "volume_ratio": volume_ratio,
            },
        }
    
    def identify_known_unknowns(
        self,
        current_data: Dict[str, Any],
    ) -> List[str]:
        """
        Identify what the system knows it doesn't know.
        
        This is crucial for risk management:
        - Don't trade when you know you're missing information
        - Size positions based on uncertainty
        """
        unknowns = []
        
        # Check data quality
        if current_data.get("data_freshness_seconds", 0) > 60:
            unknowns.append("Stale market data (>60s old)")
        
        if current_data.get("order_book_depth", 0) < 10:
            unknowns.append("Shallow order book (<10 levels)")
        
        if current_data.get("volume_24h", 0) < 1000000:
            unknowns.append("Low liquidity (<$1M 24h volume)")
        
        # Check regime confidence
        if self.state.regime_confidence < 0.5:
            unknowns.append(f"Uncertain regime (confidence={self.state.regime_confidence:.2f})")
        
        # Check calibration
        if self.state.confidence_calibration < 0.6:
            unknowns.append("Poorly calibrated predictions")
        
        # Check recent mistakes
        if len(self.state.recent_mistakes) > 10:
            recent_error_rate = sum(1 for m in self.state.recent_mistakes[-20:] if True) / 20
            if recent_error_rate > 0.6:
                unknowns.append(f"High recent error rate ({recent_error_rate:.0%})")
        
        self.state.known_unknowns = unknowns
        return unknowns
    
    def calculate_position_size(
        self,
        base_size: float,
        confidence: float,
        regime: str,
        known_unknowns: List[str],
    ) -> float:
        """
        Calculate optimal position size based on self-awareness.
        
        Reduces size when:
        - Low confidence
        - Uncertain regime
        - Known unknowns present
        - Poor calibration
        """
        multiplier = 1.0
        
        # Confidence adjustment
        multiplier *= confidence
        
        # Regime adjustment
        regime_multipliers = {
            "trending": 1.2,
            "high_volatility": 0.7,
            "low_volatility": 0.8,
            "ranging": 0.9,
            "downtrend": 0.6,
        }
        multiplier *= regime_multipliers.get(regime, 0.8)
        
        # Known unknowns penalty
        multiplier *= max(0.3, 1 - len(known_unknowns) * 0.15)
        
        # Calibration adjustment
        multiplier *= self.state.confidence_calibration
        
        # Apply
        adjusted_size = base_size * multiplier
        
        return max(0, adjusted_size)
    
    def get_meta_score(self) -> float:
        """Calculate overall meta-cognition score."""
        scores = []
        
        # Calibration score
        scores.append(self.state.confidence_calibration)
        
        # Regime detection confidence
        scores.append(self.state.regime_confidence)
        
        # Mistake rate (inverse)
        if self.state.recent_mistakes:
            mistake_rate = len(self.state.recent_mistakes) / max(1, len(self.calibration_data))
            scores.append(max(0, 1 - mistake_rate * 2))
        else:
            scores.append(0.5)
        
        # Average
        self.state.meta_score = np.mean(scores) if scores else 0.0
        return self.state.meta_score
    
    def should_trade(
        self,
        signal_confidence: float,
        regime: str,
        known_unknowns: List[str],
    ) -> Tuple[bool, str]:
        """Determine if the system should trade right now."""
        # Don't trade with too many unknowns
        if len(known_unknowns) > 5:
            return False, "Too many known unknowns"
        
        # Don't trade with low confidence
        if signal_confidence < 0.4:
            return False, "Signal confidence too low"
        
        # Don't trade in uncertain regime with low calibration
        if regime == "unknown" and self.state.confidence_calibration < 0.5:
            return False, "Uncertain regime and poor calibration"
        
        # Don't trade after many recent mistakes
        if len(self.state.recent_mistakes) > 15:
            return False, "Too many recent mistakes - cooling off"
        
        return True, "OK to trade"


# ============================================================================
# AUTONOMOUS RESEARCH LAB
# ============================================================================

class AutonomousResearchLab:
    """
    Autonomous research laboratory for trading strategies.
    
    Key capabilities:
    - Hypothesis generation (come up with new ideas)
    - Experimental design (test ideas properly)
    - Backtesting (validate ideas against history)
    - Paper generation (document findings)
    - Peer review (validate against market reality)
    
    This is the engine of continuous improvement:
    The system never stops generating and testing new ideas.
    """
    
    def __init__(self):
        self.hypotheses: Dict[str, ResearchHypothesis] = {}
        self.experiments: List[Dict] = []
        self.findings: List[Dict] = []
        self.hypothesis_counter = 0
        
        logger.info("Autonomous Research Lab initialized")
    
    def generate_hypothesis(
        self,
        market_conditions: Dict[str, Any],
        existing_findings: Optional[List[Dict]] = None,
    ) -> ResearchHypothesis:
        """
        Generate a new research hypothesis.
        
        Uses existing findings and market conditions to propose
        new ideas worth testing.
        """
        self.hypothesis_counter += 1
        
        # Generate hypothesis based on patterns
        hypothesis_types = [
            self._generate_momentum_hypothesis,
            self._generate_mean_reversion_hypothesis,
            self._generate_cross_asset_hypothesis,
            self._generate_volatility_hypothesis,
            self._generate_sentiment_hypothesis,
        ]
        
        # Pick based on market conditions
        volatility = market_conditions.get("volatility", 0.02)
        trend = market_conditions.get("trend_strength", 0.0)
        
        if volatility > 0.03:
            generator = self._generate_volatility_hypothesis
        elif abs(trend) > 0.5:
            generator = self._generate_momentum_hypothesis
        else:
            generator = np.random.choice(hypothesis_types)
        
        hypothesis = generator(market_conditions)
        
        self.hypotheses[hypothesis.id] = hypothesis
        
        logger.info(
            "Generated hypothesis: %s (priority=%d)",
            hypothesis.statement[:50],
            hypothesis.priority,
        )
        
        return hypothesis
    
    def _generate_momentum_hypothesis(
        self,
        conditions: Dict[str, Any],
    ) -> ResearchHypothesis:
        """Generate momentum-based hypothesis."""
        self.hypothesis_counter += 1
        
        return ResearchHypothesis(
            id=f"hyp_{self.hypothesis_counter:04d}",
            statement="Assets that outperform by >5% in 7 days will continue outperforming by >2% in the next 3 days",
            test_plan=[
                "1. Select top 20% performers by 7-day return",
                "2. Track their 3-day forward returns",
                "3. Compare to bottom 20% performers",
                "4. Test across different market regimes",
            ],
            expected_outcome="Momentum persists in trending markets, reverses in ranging markets",
            confidence=0.6,
            priority=7,
        )
    
    def _generate_mean_reversion_hypothesis(
        self,
        conditions: Dict[str, Any],
    ) -> ResearchHypothesis:
        """Generate mean reversion hypothesis."""
        self.hypothesis_counter += 1
        
        return ResearchHypothesis(
            id=f"hyp_{self.hypothesis_counter:04d}",
            statement="Assets that drop >10% in 1 day will recover >3% within 3 days (excluding regime changes)",
            test_plan=[
                "1. Identify all >10% single-day drops",
                "2. Filter out regime change events",
                "3. Track 3-day forward returns",
                "4. Calculate win rate and average return",
            ],
            expected_outcome="Mean reversion works in stable regimes, fails in regime changes",
            confidence=0.5,
            priority=8,
        )
    
    def _generate_cross_asset_hypothesis(
        self,
        conditions: Dict[str, Any],
    ) -> ResearchHypothesis:
        """Generate cross-asset hypothesis."""
        self.hypothesis_counter += 1
        
        return ResearchHypothesis(
            id=f"hyp_{self.hypothesis_counter:04d}",
            statement="When BTC rises >3% in 4 hours, ETH will rise >2% within 8 hours with 70% probability",
            test_plan=[
                "1. Find all BTC >3% moves in 4h windows",
                "2. Check ETH returns in following 8h",
                "3. Calculate conditional probability",
                "4. Test across different time periods",
            ],
            expected_outcome="Cross-asset lead-lag relationship exists with exploitable edge",
            confidence=0.55,
            priority=6,
        )
    
    def _generate_volatility_hypothesis(
        self,
        conditions: Dict[str, Any],
    ) -> ResearchHypothesis:
        """Generate volatility-based hypothesis."""
        self.hypothesis_counter += 1
        
        return ResearchHypothesis(
            id=f"hyp_{self.hypothesis_counter:04d}",
            statement="When 30-day volatility doubles from recent lows, returns will be negative over next 7 days",
            test_plan=[
                "1. Calculate 30-day rolling volatility",
                "2. Identify when volatility doubles from 60-day low",
                "3. Track 7-day forward returns",
                "4. Test across multiple assets",
            ],
            expected_outcome="Volatility expansion predicts negative returns due to risk-off sentiment",
            confidence=0.65,
            priority=9,
        )
    
    def _generate_sentiment_hypothesis(
        self,
        conditions: Dict[str, Any],
    ) -> ResearchHypothesis:
        """Generate sentiment-based hypothesis."""
        self.hypothesis_counter += 1
        
        return ResearchHypothesis(
            id=f"hyp_{self.hypothesis_counter:04d}",
            statement="Extreme negative sentiment (>2 std below mean) predicts positive returns over next 5 days",
            test_plan=[
                "1. Calculate daily sentiment score from news/social",
                "2. Identify extreme negative sentiment days",
                "3. Track 5-day forward returns",
                "4. Compare to normal sentiment days",
            ],
            expected_outcome="Contrarian sentiment strategy works at extremes",
            confidence=0.5,
            priority=7,
        )
    
    def test_hypothesis(
        self,
        hypothesis_id: str,
        data: Dict[str, np.ndarray],
    ) -> Dict[str, Any]:
        """
        Test a hypothesis against market data.
        
        Returns test results including statistical significance.
        """
        if hypothesis_id not in self.hypotheses:
            return {"error": "Hypothesis not found"}
        
        hypothesis = self.hypotheses[hypothesis_id]
        
        # Run backtest based on hypothesis type
        results = self._run_backtest(hypothesis, data)
        
        # Update hypothesis
        hypothesis.results = results
        hypothesis.status = "tested"
        
        # Store finding
        if results.get("profitable", False):
            self.findings.append({
                "hypothesis_id": hypothesis_id,
                "statement": hypothesis.statement,
                "results": results,
                "timestamp": datetime.now().isoformat(),
            })
        
        return results
    
    def _run_backtest(
        self,
        hypothesis: ResearchHypothesis,
        data: Dict[str, np.ndarray],
    ) -> Dict[str, Any]:
        """Run a simplified backtest."""
        # Simplified backtest - in production would be more sophisticated
        
        returns = data.get("returns", np.random.randn(252) * 0.02)
        
        # Simple momentum strategy
        lookback = 7
        forward = 3
        
        signals = []
        actual_returns = []
        
        for i in range(lookback, len(returns) - forward):
            past_return = np.sum(returns[i-lookback:i])
            future_return = np.sum(returns[i:i+forward])
            
            if past_return > 0.05:  # >5% in lookback
                signals.append(1)  # Long
                actual_returns.append(future_return)
            elif past_return < -0.05:
                signals.append(-1)  # Short
                actual_returns.append(-future_return)
        
        if not signals:
            return {"error": "No signals generated"}
        
        signals = np.array(signals)
        actual_returns = np.array(actual_returns)
        
        # Calculate metrics
        strategy_returns = signals * actual_returns
        total_return = np.sum(strategy_returns)
        win_rate = np.mean(strategy_returns > 0)
        sharpe = np.mean(strategy_returns) / (np.std(strategy_returns) + 1e-10) * np.sqrt(252/forward)
        
        return {
            "total_return": float(total_return),
            "win_rate": float(win_rate),
            "sharpe_ratio": float(sharpe),
            "n_trades": len(signals),
            "profitable": total_return > 0,
            "avg_return_per_trade": float(np.mean(strategy_returns)),
            "max_drawdown": float(np.min(np.cumsum(strategy_returns))),
        }
    
    def generate_paper(
        self,
        hypothesis_id: str,
    ) -> str:
        """Generate a research paper documenting findings."""
        if hypothesis_id not in self.hypotheses:
            return "Hypothesis not found"
        
        hypothesis = self.hypotheses[hypothesis_id]
        results = hypothesis.results or {}
        
        paper = f"""
# Research Paper: {hypothesis.statement}

## Abstract
This paper investigates the following hypothesis: {hypothesis.statement}

## Methodology
{chr(10).join(hypothesis.test_plan)}

## Results
- Total Return: {results.get('total_return', 0)*100:.2f}%
- Win Rate: {results.get('win_rate', 0)*100:.1f}%
- Sharpe Ratio: {results.get('sharpe_ratio', 0):.2f}
- Number of Trades: {results.get('n_trades', 0)}

## Conclusion
The hypothesis {'was' if results.get('profitable') else 'was not'} supported by the data.
{hypothesis.expected_outcome}

## Confidence
Initial confidence: {hypothesis.confidence:.0%}
Statistical significance: {'Yes' if results.get('sharpe_ratio', 0) > 1.5 else 'No'}

---
Generated by Argus Autonomous Research Lab
"""
        
        return paper
    
    def get_top_hypotheses(
        self,
        n: int = 5,
        status: Optional[str] = None,
    ) -> List[ResearchHypothesis]:
        """Get top hypotheses by priority."""
        hypotheses = list(self.hypotheses.values())
        
        if status:
            hypotheses = [h for h in hypotheses if h.status == status]
        
        hypotheses.sort(key=lambda h: h.priority, reverse=True)
        
        return hypotheses[:n]


# ============================================================================
# LEVEL 20 SINGULARITY ORCHESTRATOR
# ============================================================================

class Level20Singularity:
    """
    The ultimate trading system - Level 20 Singularity.
    
    Combines all advanced components:
    - Causal Discovery Engine
    - Predictive Order Flow Engine
    - Cross-Market System
    - Self-Aware System
    - Autonomous Research Lab
    
    This represents the theoretical maximum of what's possible
    in algorithmic trading.
    """
    
    def __init__(self):
        # Initialize all components
        self.causal_engine = CausalDiscoveryEngine()
        self.order_flow = PredictiveOrderFlowEngine()
        self.cross_market = CrossMarketSystem()
        self.self_aware = SelfAwareSystem()
        self.research_lab = AutonomousResearchLab()
        
        # System state
        self.cycle_count = 0
        self.total_signals = 0
        self.total_pnl = 0.0
        
        logger.info("=" * 60)
        logger.info("LEVEL 20 SINGULARITY INITIALIZED")
        logger.info("=" * 60)
        logger.info("Components:")
        logger.info("  - Causal Discovery Engine")
        logger.info("  - Predictive Order Flow Engine")
        logger.info("  - Cross-Market System")
        logger.info("  - Self-Aware System")
        logger.info("  - Autonomous Research Lab")
        logger.info("=" * 60)
    
    def analyze_market(
        self,
        market_data: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Complete market analysis using all Level 20 components.
        
        Returns comprehensive analysis with:
        - Causal relationships
        - Order flow predictions
        - Cross-market signals
        - Self-awareness assessment
        - Research hypotheses
        """
        self.cycle_count += 1
        
        analysis = {
            "cycle": self.cycle_count,
            "timestamp": datetime.now().isoformat(),
        }
        
        # 1. Causal Discovery
        if "price_series" in market_data:
            causal_edges = self.causal_engine.discover_causal_structure(
                market_data["price_series"],
                max_lag=5,
            )
            analysis["causal_discovery"] = {
                "n_edges": len(causal_edges),
                "top_edges": [e.to_dict() for e in causal_edges[:5]],
            }
        
        # 2. Order Flow Analysis
        if "order_book" in market_data:
            ob = market_data["order_book"]
            events = self.order_flow.analyze_order_book(
                symbol=ob.get("symbol", "BTC"),
                bids=ob.get("bids", []),
                asks=ob.get("asks", []),
            )
            analysis["order_flow"] = {
                "n_events": len(events),
                "events": [e.to_dict() for e in events],
                "prediction": self.order_flow.predict_order_flow(ob.get("symbol", "BTC")),
            }
        
        # 3. Cross-Market Analysis
        if "cross_market_prices" in market_data:
            correlation_regime = self.cross_market.analyze_correlation_regime(
                market_data["cross_market_prices"]
            )
            analysis["cross_market"] = correlation_regime
        
        # 4. Self-Awareness Assessment
        known_unknowns = self.self_aware.identify_known_unknowns(market_data)
        regime = self.self_aware.detect_regime(market_data)
        should_trade, reason = self.self_aware.should_trade(
            signal_confidence=market_data.get("signal_confidence", 0.5),
            regime=regime["regime"],
            known_unknowns=known_unknowns,
        )
        
        analysis["self_awareness"] = {
            "regime": regime,
            "known_unknowns": known_unknowns,
            "should_trade": should_trade,
            "trade_reason": reason,
            "meta_score": self.self_aware.get_meta_score(),
        }
        
        # 5. Research Hypotheses
        hypothesis = self.research_lab.generate_hypothesis(market_data)
        analysis["research"] = {
            "new_hypothesis": {
                "id": hypothesis.id,
                "statement": hypothesis.statement,
                "priority": hypothesis.priority,
            },
            "total_hypotheses": len(self.research_lab.hypotheses),
            "findings": len(self.research_lab.findings),
        }
        
        return analysis
    
    def get_system_report(self) -> Dict[str, Any]:
        """Get comprehensive system report."""
        return {
            "system": "Level 20 Singularity",
            "version": "1.0.0",
            "cycle_count": self.cycle_count,
            "total_signals": self.total_signals,
            "total_pnl": self.total_pnl,
            "components": {
                "causal_engine": {
                    "edges_discovered": sum(len(edges) for edges in self.causal_engine.causal_graph.values()),
                    "history_entries": len(self.causal_engine.history),
                },
                "order_flow": {
                    "events_detected": len(self.order_flow.detected_events),
                    "history_size": len(self.order_flow.order_history),
                },
                "cross_market": {
                    "markets_enabled": sum(1 for m in self.cross_market.markets.values() if m["enabled"]),
                    "signals_generated": len(self.cross_market.signals),
                },
                "self_aware": {
                    "meta_score": self.self_aware.get_meta_score(),
                    "calibration": self.self_aware.state.confidence_calibration,
                    "regime": self.self_aware.state.current_regime,
                },
                "research_lab": {
                    "hypotheses": len(self.research_lab.hypotheses),
                    "findings": len(self.research_lab.findings),
                },
            },
        }


# ============================================================================
# FACTORY FUNCTIONS
# ============================================================================

def create_level20_singularity() -> Level20Singularity:
    """Create Level 20 Singularity system."""
    return Level20Singularity()


def create_causal_engine() -> CausalDiscoveryEngine:
    """Create Causal Discovery Engine."""
    return CausalDiscoveryEngine()


def create_order_flow_engine() -> PredictiveOrderFlowEngine:
    """Create Predictive Order Flow Engine."""
    return PredictiveOrderFlowEngine()


def create_cross_market_system() -> CrossMarketSystem:
    """Create Cross-Market System."""
    return CrossMarketSystem()


def create_self_aware_system() -> SelfAwareSystem:
    """Create Self-Aware System."""
    return SelfAwareSystem()


def create_research_lab() -> AutonomousResearchLab:
    """Create Autonomous Research Lab."""
    return AutonomousResearchLab()
