[global]
tx_timestamp_timeout 50
clock_servo pi
pi_proportional_const 0.0
pi_integral_const 0.0
step_threshold 0.00002
delay_mechanism E2E
network_transport UDPv4
time_stamping hardware
summary_interval 0

[enp3s0f0]
